Deep Lerning. We will search G1, G2 and after G3.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, Concatenate
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

In [2]:
student_performance = fetch_ucirepo(id=320) 

data_X = student_performance.data.features
data_y = student_performance.data.targets

X = pd.get_dummies(data_X)
y = data_y

# При использовании pd.get_dummies для преобразования категориальных признаков в dummy-переменные, нет необходимости в явном использовании слоя нормализации в модели. 
# Это потому, что pd.get_dummies создает бинарные (или dummy) переменные, которые по своей природе уже нормализованы (их значения находятся в диапазоне [0, 1]).
# слой Flatten так же не нужен

In [3]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
x_train = x_train.astype(float)
x_test = x_test.astype(float)

y_train = y_train.astype(float)
y_test = y_test.astype(float)

In [5]:
input_scores = Input(shape=(x_train.shape[1],))

# Слои для предсказания g1
dense_g1 = Dense(32, activation="relu")(input_scores)
output_g1 = Dense(1)(dense_g1)

# Слои для предсказания g2 (используя input_scores и g1)
concat_g2 = Concatenate()([input_scores, output_g1])
dense_g2 = Dense(32, activation="relu")(concat_g2)
output_g2 = Dense(1)(dense_g2)

# Слои для предсказания g3 (используя input_scores, g1 и g2)
concat_g3 = Concatenate()([input_scores, output_g1, output_g2])
dense_g3 = Dense(32, activation="relu")(concat_g3)
output_g3 = Dense(1)(dense_g3)

model = Model(inputs=input_scores, outputs=[output_g1, output_g2, output_g3])

In [6]:
model.compile(optimizer="adam", loss="mse", metrics=["mse", "mse", "mse"])

In [7]:
model.fit(x_train, [y_train['G1'], y_train['G2'], y_train['G3']], epochs=500)

Epoch 1/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - dense_1_mse: 101.8845 - dense_3_mse: 98.8554 - dense_5_mse: 225.5590 - loss: 426.2989
Epoch 2/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - dense_1_mse: 58.0821 - dense_3_mse: 31.0875 - dense_5_mse: 110.5793 - loss: 199.7490
Epoch 3/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - dense_1_mse: 26.2511 - dense_3_mse: 12.9621 - dense_5_mse: 46.9322 - loss: 86.1453
Epoch 4/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - dense_1_mse: 11.5363 - dense_3_mse: 13.0845 - dense_5_mse: 19.0755 - loss: 43.6964
Epoch 5/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - dense_1_mse: 8.3635 - dense_3_mse: 10.4663 - dense_5_mse: 12.8065 - loss: 31.6363
Epoch 6/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 7.9941 - dense_3_mse: 9.4792 - dense_5_mse: 11.8347 - loss: 29.3080
Epoch 7/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - dense_1_mse: 7.9347 - dense_3_mse: 9.9063 - dense_5_mse: 12.5397 - loss: 30.3807
Epoch 8/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 7.0112 - dense_3_mse: 8.6108 - dense_5_mse: 11.1199 - loss: 26.7419
Epoch 9/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - dense_1_mse: 7.5593 - dense_3_mse: 8.0407 - dense_5_mse: 10.9845 - loss: 26.5845
Epoch 10/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - dense_1_mse: 7.2706 - dense_3_mse: 7.5592 - dense_5_mse: 10.3587 - loss: 25.1885
Epoch 11/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - dense_1_mse: 6.8944 - dense_3_mse: 7.9501 - dense_5_mse: 10.8589 - loss: 25.7033
Epoch 12/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 6.8648 - dense_3_mse: 8.1172 - dense_5_mse: 10.6387 - loss: 25.6207
Epoch 13/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - dense_1_mse: 6.2690 - dense_3_mse: 7.1026 - dense_5_mse: 9.1190 - loss: 22.4906
Epoch 14/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.7000 - dense_3_mse: 6.2477 - dense_5_mse: 7.9972 - loss: 19.9449
Epoch 15/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - dense_1_mse: 6.1680 - dense_3_mse: 5.7176 - dense_5_mse: 8.1402 - loss: 20.0258
Epoch 16/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.6748 - dense_3_mse: 6.3910 - dense_5_mse: 9.5569 - loss: 21.6227
Epoch 17/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - dense_1_mse: 5.6344 - dense_3_mse: 6.3700 - dense_5_mse: 9.1171 - loss: 21.1215
Epoch 18/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.9645 - dense_3_mse: 6.2890 - dense_5_mse: 8.9072 - loss: 21.1607
Epoch 19/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - dense_1_mse: 5.4299 - dense_3_mse: 5.7228 - dense_5_mse: 7.2262 - loss: 18.3788
Epoch 20/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 6.0536 - dense_3_mse: 5.7517 - dense_5_mse: 8.7573 - loss: 20.5625
Epoch 21/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 5.0344 - dense_3_mse: 6.2906 - dense_5_mse: 8.3165 - loss: 19.6415
Epoch 22/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.6341 - dense_3_mse: 6.2719 - dense_5_mse: 9.0745 - loss: 20.9805
Epoch 23/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.4669 - dense_3_mse: 6.0958 - dense_5_mse: 7.8798 - loss: 19.4424
Epoch 24/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.9011 - dense_3_mse: 5.6090 - dense_5_mse: 7.4233 - loss: 17.9334
Epoch 25/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 4.8359 - dense_3_mse: 4.6122 - dense_5_mse: 6.5935 - loss: 16.0416
Epoch 26/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.1142 - dense_3_mse: 5.9565 - dense_5_mse: 7.4210 - loss: 18.4917
Epoch 27/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 4.8157 - dense_3_mse: 5.1704 - dense_5_mse: 6.5261 - loss: 16.5122
Epoch 28/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - dense_1_mse: 4.8641 - dense_3_mse: 5.4103 - dense_5_mse: 7.7455 - loss: 18.0198
Epoch 29/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - dense_1_mse: 5.2223 - dense_3_mse: 5.0644 - dense_5_mse: 5.7100 - loss: 15.9967
Epoch 30/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - dense_1_mse: 5.0938 - dense_3_mse: 5.1655 - dense_5_mse: 7.1202 - loss: 17.3795
Epoch 31/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - dense_1_mse: 4.7258 - dense_3_mse: 5.9805 - dense_5_mse: 7.7655 - loss: 18.4717
Epoch 32/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - dense_1_mse: 4.3465 - dense_3_mse: 5.2684 - dense_5_mse: 7.2713 - loss: 16.8862
Epoch 33/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - dense_1_mse: 4.9719 - dense_3_mse: 5.4858 - dense_5_mse: 7.2669 - loss: 17.7246
Epoch 34/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - dense_1_mse: 5.2979 - dense_3_mse: 5.8985 - dense_5_mse: 7.5967 - loss: 18.7931
Epoch 35/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.4166 - dense_3_mse: 4.8688 - dense_5_mse: 6.8675 - loss: 16.1529
Epoch 36/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - dense_1_mse: 5.0988 - dense_3_mse: 5.0807 - dense_5_mse: 7.1263 - loss: 17.3057
Epoch 37/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - dense_1_mse: 4.7627 - dense_3_mse: 5.1241 - dense_5_mse: 6.8613 - loss: 16.7481
Epoch 38/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - dense_1_mse: 4.6556 - dense_3_mse: 4.8618 - dense_5_mse: 6.0823 - loss: 15.5996
Epoch 39/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - dense_1_mse: 4.3846 - dense_3_mse: 4.8477 - dense_5_mse: 6.8419 - loss: 16.0741
Epoch 40/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.9808 - dense_3_mse: 4.9483 - dense_5_mse: 5.8625 - loss: 14.7917
Epoch 41/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - dense_1_mse: 4.6882 - dense_3_mse: 4.9307 - dense_5_mse: 6.5735 - loss: 16.1925
Epoch 42/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - dense_1_mse: 4.4229 - dense_3_mse: 4.8473 - dense_5_mse: 6.2913 - loss: 15.5615
Epoch 43/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - dense_1_mse: 4.5900 - dense_3_mse: 5.4389 - dense_5_mse: 5.9922 - loss: 16.0210
Epoch 44/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.6501 - dense_3_mse: 4.9187 - dense_5_mse: 6.2863 - loss: 15.8552
Epoch 45/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.7317 - dense_3_mse: 5.0620 - dense_5_mse: 6.3003 - loss: 16.0940
Epoch 46/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.6269 - dense_3_mse: 4.6701 - dense_5_mse: 6.5566 - loss: 15.8537
Epoch 47/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - dense_1_mse: 4.7975 - dense_3_mse: 4.9622 - dense_5_mse: 6.2145 - loss: 15.9742
Epoch 48/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.4582 - dense_3_mse: 4.3083 - dense_5_mse: 5.6572 - loss: 14.4237
Epoch 49/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.7035 - dense_3_mse: 5.2001 - dense_5_mse: 6.8980 - loss: 16.8016
Epoch 50/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1204 - dense_3_mse: 5.1280 - dense_5_mse: 6.3786 - loss: 15.6271
Epoch 51/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.6466 - dense_3_mse: 4.6599 - dense_5_mse: 6.6151 - loss: 15.9215
Epoch 52/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 4.6716 - dense_3_mse: 4.9700 - dense_5_mse: 6.7082 - loss: 16.3498
Epoch 53/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1559 - dense_3_mse: 4.6896 - dense_5_mse: 6.3088 - loss: 15.1543
Epoch 54/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.5470 - dense_3_mse: 5.0702 - dense_5_mse: 6.5380 - loss: 16.1552
Epoch 55/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - dense_1_mse: 4.6287 - dense_3_mse: 4.3139 - dense_5_mse: 5.7772 - loss: 14.7198
Epoch 56/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - dense_1_mse: 3.9562 - dense_3_mse: 4.2831 - dense_5_mse: 5.0995 - loss: 13.3388
Epoch 57/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - dense_1_mse: 4.5619 - dense_3_mse: 5.3834 - dense_5_mse: 6.6806 - loss: 16.6259
Epoch 58/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.7420 - dense_3_mse: 4.8199 - dense_5_mse: 6.5550 - loss: 16.1169
Epoch 59/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - dense_1_mse: 4.2932 - dense_3_mse: 4.9144 - dense_5_mse: 6.7051 - loss: 15.9127
Epoch 60/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - dense_1_mse: 4.3204 - dense_3_mse: 4.7932 - dense_5_mse: 6.0662 - loss: 15.1798
Epoch 61/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2351 - dense_3_mse: 4.2364 - dense_5_mse: 5.4295 - loss: 13.9010
Epoch 62/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - dense_1_mse: 4.6276 - dense_3_mse: 4.7638 - dense_5_mse: 6.8782 - loss: 16.2697
Epoch 63/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - dense_1_mse: 3.9531 - dense_3_mse: 4.7345 - dense_5_mse: 5.5425 - loss: 14.2302
Epoch 64/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1568 - dense_3_mse: 4.8783 - dense_5_mse: 6.2803 - loss: 15.3154
Epoch 65/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - dense_1_mse: 4.3355 - dense_3_mse: 4.6068 - dense_5_mse: 5.9888 - loss: 14.9310
Epoch 66/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1666 - dense_3_mse: 4.8344 - dense_5_mse: 5.8333 - loss: 14.8342
Epoch 67/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - dense_1_mse: 4.3623 - dense_3_mse: 4.6342 - dense_5_mse: 5.9900 - loss: 14.9865
Epoch 68/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - dense_1_mse: 4.4394 - dense_3_mse: 4.7261 - dense_5_mse: 5.4778 - loss: 14.6433
Epoch 69/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - dense_1_mse: 4.5105 - dense_3_mse: 5.3458 - dense_5_mse: 6.4827 - loss: 16.3390
Epoch 70/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1227 - dense_3_mse: 4.6090 - dense_5_mse: 5.6740 - loss: 14.4057
Epoch 71/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.6614 - dense_3_mse: 4.7469 - dense_5_mse: 6.7733 - loss: 16.1816
Epoch 72/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - dense_1_mse: 4.7466 - dense_3_mse: 4.8082 - dense_5_mse: 5.7597 - loss: 15.3145
Epoch 73/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - dense_1_mse: 4.8402 - dense_3_mse: 4.7646 - dense_5_mse: 6.6510 - loss: 16.2558
Epoch 74/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - dense_1_mse: 4.4258 - dense_3_mse: 4.9049 - dense_5_mse: 6.3894 - loss: 15.7202
Epoch 75/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - dense_1_mse: 4.3441 - dense_3_mse: 4.5751 - dense_5_mse: 6.1213 - loss: 15.0406
Epoch 76/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - dense_1_mse: 4.5861 - dense_3_mse: 4.7431 - dense_5_mse: 5.9062 - loss: 15.2353
Epoch 77/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - dense_1_mse: 5.0365 - dense_3_mse: 4.9476 - dense_5_mse: 6.1524 - loss: 16.1364
Epoch 78/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2631 - dense_3_mse: 4.5701 - dense_5_mse: 5.7547 - loss: 14.5879
Epoch 79/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - dense_1_mse: 4.3183 - dense_3_mse: 4.5973 - dense_5_mse: 6.1436 - loss: 15.0592
Epoch 80/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.6752 - dense_3_mse: 5.3326 - dense_5_mse: 6.0903 - loss: 16.0981
Epoch 81/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2924 - dense_3_mse: 4.7482 - dense_5_mse: 5.5887 - loss: 14.6293
Epoch 82/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3462 - dense_3_mse: 4.6255 - dense_5_mse: 5.8916 - loss: 14.8633
Epoch 83/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2424 - dense_3_mse: 5.0720 - dense_5_mse: 6.1740 - loss: 15.4883
Epoch 84/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.4919 - dense_3_mse: 5.1224 - dense_5_mse: 6.3940 - loss: 16.0083
Epoch 85/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - dense_1_mse: 4.3664 - dense_3_mse: 4.9899 - dense_5_mse: 5.5219 - loss: 14.8781
Epoch 86/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2540 - dense_3_mse: 5.0314 - dense_5_mse: 6.3891 - loss: 15.6744
Epoch 87/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - dense_1_mse: 3.9281 - dense_3_mse: 4.0805 - dense_5_mse: 5.0594 - loss: 13.0680
Epoch 88/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.6668 - dense_3_mse: 5.0741 - dense_5_mse: 6.1001 - loss: 15.8410
Epoch 89/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.4034 - dense_3_mse: 4.8069 - dense_5_mse: 5.4804 - loss: 14.6906
Epoch 90/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0598 - dense_3_mse: 4.9062 - dense_5_mse: 5.8561 - loss: 14.8221
Epoch 91/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3389 - dense_3_mse: 4.8263 - dense_5_mse: 5.5589 - loss: 14.7240
Epoch 92/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - dense_1_mse: 4.2458 - dense_3_mse: 4.9087 - dense_5_mse: 5.5002 - loss: 14.6548
Epoch 93/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1490 - dense_3_mse: 4.9374 - dense_5_mse: 7.0163 - loss: 16.1028
Epoch 94/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - dense_1_mse: 4.2863 - dense_3_mse: 4.8342 - dense_5_mse: 5.8323 - loss: 14.9529
Epoch 95/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - dense_1_mse: 4.3803 - dense_3_mse: 4.5863 - dense_5_mse: 5.6951 - loss: 14.6618
Epoch 96/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - dense_1_mse: 4.8585 - dense_3_mse: 4.9957 - dense_5_mse: 6.1831 - loss: 16.0373
Epoch 97/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.5216 - dense_3_mse: 4.0898 - dense_5_mse: 5.0147 - loss: 13.6262
Epoch 98/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - dense_1_mse: 4.4924 - dense_3_mse: 4.8648 - dense_5_mse: 5.5766 - loss: 14.9337
Epoch 99/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.4785 - dense_3_mse: 4.8236 - dense_5_mse: 5.0715 - loss: 14.3737
Epoch 100/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - dense_1_mse: 4.1725 - dense_3_mse: 4.7489 - dense_5_mse: 5.7136 - loss: 14.6350
Epoch 101/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - dense_1_mse: 4.4118 - dense_3_mse: 4.8290 - dense_5_mse: 5.2413 - loss: 14.4821
Epoch 102/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - dense_1_mse: 4.0986 - dense_3_mse: 4.9697 - dense_5_mse: 6.2168 - loss: 15.2852
Epoch 103/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2746 - dense_3_mse: 4.3277 - dense_5_mse: 5.2111 - loss: 13.8134
Epoch 104/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - dense_1_mse: 3.9073 - dense_3_mse: 4.7754 - dense_5_mse: 5.5388 - loss: 14.2214
Epoch 105/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - dense_1_mse: 4.1989 - dense_3_mse: 4.7075 - dense_5_mse: 5.8289 - loss: 14.7353
Epoch 106/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - dense_1_mse: 3.9904 - dense_3_mse: 4.2675 - dense_5_mse: 5.4865 - loss: 13.7445
Epoch 107/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - dense_1_mse: 4.2568 - dense_3_mse: 4.1864 - dense_5_mse: 5.2840 - loss: 13.7272
Epoch 108/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - dense_1_mse: 4.8375 - dense_3_mse: 4.9507 - dense_5_mse: 6.1917 - loss: 15.9800
Epoch 109/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2813 - dense_3_mse: 4.4534 - dense_5_mse: 5.6115 - loss: 14.3463
Epoch 110/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2051 - dense_3_mse: 4.6093 - dense_5_mse: 6.4814 - loss: 15.2958
Epoch 111/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - dense_1_mse: 4.5566 - dense_3_mse: 4.4361 - dense_5_mse: 5.2653 - loss: 14.2580
Epoch 112/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - dense_1_mse: 4.1971 - dense_3_mse: 4.3894 - dense_5_mse: 5.7310 - loss: 14.3175
Epoch 113/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - dense_1_mse: 4.6050 - dense_3_mse: 5.0975 - dense_5_mse: 6.1088 - loss: 15.8112
Epoch 114/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - dense_1_mse: 4.7283 - dense_3_mse: 4.0182 - dense_5_mse: 5.1843 - loss: 13.9308
Epoch 115/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.7353 - dense_3_mse: 3.7134 - dense_5_mse: 4.8568 - loss: 12.3055
Epoch 116/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - dense_1_mse: 3.9891 - dense_3_mse: 4.7908 - dense_5_mse: 6.3493 - loss: 15.1292
Epoch 117/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - dense_1_mse: 4.3126 - dense_3_mse: 4.6707 - dense_5_mse: 5.6227 - loss: 14.6060
Epoch 118/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - dense_1_mse: 4.5858 - dense_3_mse: 5.1931 - dense_5_mse: 6.5083 - loss: 16.2872
Epoch 119/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - dense_1_mse: 5.0812 - dense_3_mse: 4.7847 - dense_5_mse: 5.7319 - loss: 15.5978
Epoch 120/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - dense_1_mse: 4.6369 - dense_3_mse: 4.8066 - dense_5_mse: 5.6976 - loss: 15.1411
Epoch 121/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - dense_1_mse: 4.7336 - dense_3_mse: 4.9783 - dense_5_mse: 6.3333 - loss: 16.0452
Epoch 122/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - dense_1_mse: 3.9630 - dense_3_mse: 4.3845 - dense_5_mse: 5.2967 - loss: 13.6441
Epoch 123/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - dense_1_mse: 3.9236 - dense_3_mse: 4.4229 - dense_5_mse: 5.8938 - loss: 14.2403
Epoch 124/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - dense_1_mse: 4.3698 - dense_3_mse: 4.4277 - dense_5_mse: 5.5052 - loss: 14.3027
Epoch 125/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - dense_1_mse: 4.2292 - dense_3_mse: 4.2585 - dense_5_mse: 5.3041 - loss: 13.7918
Epoch 126/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 4.2466 - dense_3_mse: 4.6206 - dense_5_mse: 4.8898 - loss: 13.7570
Epoch 127/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - dense_1_mse: 4.4984 - dense_3_mse: 4.6379 - dense_5_mse: 6.2821 - loss: 15.4184
Epoch 128/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - dense_1_mse: 4.1327 - dense_3_mse: 4.6764 - dense_5_mse: 5.8236 - loss: 14.6328
Epoch 129/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step - dense_1_mse: 4.6507 - dense_3_mse: 4.9697 - dense_5_mse: 6.4444 - loss: 16.0649
Epoch 130/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - dense_1_mse: 4.5882 - dense_3_mse: 4.7972 - dense_5_mse: 5.6421 - loss: 15.0274
Epoch 131/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - dense_1_mse: 4.1274 - dense_3_mse: 4.4908 - dense_5_mse: 5.1567 - loss: 13.7750
Epoch 132/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - dense_1_mse: 4.4831 - dense_3_mse: 4.8821 - dense_5_mse: 5.7062 - loss: 15.0714
Epoch 133/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - dense_1_mse: 3.6896 - dense_3_mse: 3.8926 - dense_5_mse: 4.3701 - loss: 11.9523
Epoch 134/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - dense_1_mse: 3.8678 - dense_3_mse: 4.3213 - dense_5_mse: 5.1784 - loss: 13.3675
Epoch 135/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - dense_1_mse: 4.0061 - dense_3_mse: 3.7442 - dense_5_mse: 4.4667 - loss: 12.2169
Epoch 136/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - dense_1_mse: 4.2183 - dense_3_mse: 4.6085 - dense_5_mse: 5.2457 - loss: 14.0726
Epoch 137/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step - dense_1_mse: 3.8970 - dense_3_mse: 4.6290 - dense_5_mse: 5.1286 - loss: 13.6547
Epoch 138/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 5.0065 - dense_3_mse: 4.7012 - dense_5_mse: 5.8533 - loss: 15.5609
Epoch 139/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0279 - dense_3_mse: 4.4332 - dense_5_mse: 5.0700 - loss: 13.5311
Epoch 140/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - dense_1_mse: 4.1440 - dense_3_mse: 4.1909 - dense_5_mse: 4.8945 - loss: 13.2294
Epoch 141/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.5169 - dense_3_mse: 4.4948 - dense_5_mse: 5.4891 - loss: 14.5008
Epoch 142/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step - dense_1_mse: 4.7428 - dense_3_mse: 4.2469 - dense_5_mse: 4.7283 - loss: 13.7180
Epoch 143/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.7722 - dense_3_mse: 3.8048 - dense_5_mse: 4.2168 - loss: 11.7937
Epoch 144/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - dense_1_mse: 4.4477 - dense_3_mse: 4.8122 - dense_5_mse: 5.5021 - loss: 14.7620
Epoch 145/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 4.3476 - dense_3_mse: 4.5012 - dense_5_mse: 5.2685 - loss: 14.1172
Epoch 146/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2433 - dense_3_mse: 4.4591 - dense_5_mse: 5.6462 - loss: 14.3486
Epoch 147/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.8330 - dense_3_mse: 4.0664 - dense_5_mse: 4.8493 - loss: 12.7487
Epoch 148/500

In [8]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 56)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 32)        │      1,824 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1)         │         33 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 57)        │          0 │ input_layer[0][0… │
│ (Concatenate)       │                   │            │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 32)        │      1,856 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 1)         │         33 │ dense_2[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_1       │ (None, 58)        │          0 │ input_layer[0][0… │
│ (Concatenate)       │                   │            │ dense_1[0][0],    │
│                     │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 32)        │      1,888 │ concatenate_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 1)         │         33 │ dense_4[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,003 (66.42 KB)

 Trainable params: 5,667 (22.14 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 11,336 (44.29 KB)

In [9]:
model.evaluate(x_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 8.2259 - dense_3_mse: 0.0000e+00 - dense_5_mse: 0.0000e+00 - loss: 8.2259

[8.480921745300293, 8.480921745300293, 0.0, 0.0]

In [10]:
pred = model.predict(x_train)
pred = np.clip(pred, 0, 20).astype(int) # обрезка
pd.DataFrame(pred.reshape(519, 3)) # преобразуем в двухмерный массив

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

      0   1   2
0    14  10  11
1    11   9   9
2     6   8   9
3    12  12  12
4    12  11  10
..   ..  ..  ..
514  13  13  15
515  12  13  15
516  10  13  12
517  13  13  11
518  15  10  13

[519 rows x 3 columns]

In [11]:
pd.DataFrame(data_y)

     G1  G2  G3
0     0  11  11
1     9  11  11
2    12  13  12
3    14  14  14
4    11  13  13
..   ..  ..  ..
644  10  11  10
645  15  15  16
646  11  12   9
647  10  10  10
648  10  11  11

[649 rows x 3 columns]