Deep Lerning. We will search G1, G2 and after G3.

In [329]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, Dropout, Concatenate
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

In [330]:
student_performance = fetch_ucirepo(id=320) 

data_X = student_performance.data.features
data_y = student_performance.data.targets

X = pd.get_dummies(data_X)
y = data_y


# При использовании pd.get_dummies для преобразования категориальных признаков в dummy-переменные, нет необходимости в явном использовании слоя нормализации в модели. 
# Это потому, что pd.get_dummies создает бинарные (или dummy) переменные, которые по своей природе уже нормализованы (их значения находятся в диапазоне [0, 1]).
# слой Flatten так же не нужен

In [331]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [332]:
x_train = x_train.astype(float)
x_test = x_test.astype(float)

y_train = y_train.astype(float)
y_test = y_test.astype(float)

In [333]:
input_scores = Input(shape=(x_train.shape[1],))

# Слои для предсказания g1
dense_g1 = Dense(32, activation="relu", name="dense_g1")(input_scores)
output_g1 = Dense(1, name="g1")(dense_g1)

# Слои для предсказания g2 (используя input_scores и g1)
concat_g2 = Concatenate(name="concat_g2")([input_scores, output_g1])
dense_g2 = Dense(32, activation="relu", name="dense_g2")(concat_g2)
output_g2 = Dense(1, name="g2")(dense_g2)

# Слои для предсказания g3 (используя input_scores, g1 и g2)
concat_g3 = Concatenate(name="concat_g3")([input_scores, output_g1, output_g2])
dense_g3 = Dense(32, activation="relu", name="dense_g3")(concat_g3)
output_g3 = Dense(1, name="g3")(dense_g3)

model = Model(inputs=input_scores, outputs=[output_g1, output_g2, output_g3])

In [334]:
model.compile(optimizer="adam", loss="mse", metrics=["mse", "mse", "mse"])

In [335]:
model.fit(x_train, [y_train['G1'], y_train['G2'], y_train['G3']], epochs=500)

Epoch 1/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - g1_mse: 162.5544 - g2_mse: 123.9234 - g3_mse: 131.8082 - loss: 418.2860
Epoch 2/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 85.6830 - g2_mse: 73.0039 - g3_mse: 67.3658 - loss: 226.0527
Epoch 3/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 41.4184 - g2_mse: 33.2315 - g3_mse: 24.6104 - loss: 99.2604
Epoch 4/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 18.4145 - g2_mse: 14.4979 - g3_mse: 13.0784 - loss: 45.9908
Epoch 5/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 11.9403 - g2_mse: 10.8129 - g3_mse: 11.8962 - loss: 34.6494
Epoch 6/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 11.7007 - g2_mse: 11.9789 - g3_mse: 13.4995 - loss: 37.1791
Epoch 7/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 9.9809 - g2_mse: 9.9819 - g3_mse: 12.3795 - loss: 32.3423
Epoch 8/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 9.3784 - g2_mse: 9.1317 - g3_mse: 10.0322 - loss: 28.5422
Epoch 9/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - g1_mse: 8.4073 - g2_mse: 7.8521 - g3_mse: 10.3146 - loss: 26.5740
Epoch 10/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - g1_mse: 7.9296 - g2_mse: 8.0384 - g3_mse: 9.6611 - loss: 25.6291
Epoch 11/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - g1_mse: 8.2645 - g2_mse: 7.3009 - g3_mse: 8.8673 - loss: 24.4327
Epoch 12/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 7.6918 - g2_mse: 7.0782 - g3_mse: 8.2884 - loss: 23.0583
Epoch 13/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - g1_mse: 7.0780 - g2_mse: 7.2531 - g3_mse: 8.8396 - loss: 23.1707
Epoch 14/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.8413 - g2_mse: 6.7911 - g3_mse: 8.6416 - loss: 22.2741
Epoch 15/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.6280 - g2_mse: 6.8769 - g3_mse: 7.2345 - loss: 20.7393
Epoch 16/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.9984 - g2_mse: 6.2555 - g3_mse: 7.8759 - loss: 21.1298
Epoch 17/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - g1_mse: 6.7288 - g2_mse: 6.3998 - g3_mse: 7.4079 - loss: 20.5364
Epoch 18/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.1525 - g2_mse: 6.4899 - g3_mse: 8.5176 - loss: 21.1599
Epoch 19/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.1857 - g2_mse: 6.1160 - g3_mse: 6.9628 - loss: 19.2645
Epoch 20/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.2986 - g2_mse: 5.7543 - g3_mse: 7.2419 - loss: 19.2948
Epoch 21/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.1089 - g2_mse: 6.5341 - g3_mse: 7.7432 - loss: 20.3862
Epoch 22/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 6.0861 - g2_mse: 6.7374 - g3_mse: 7.9855 - loss: 20.8090
Epoch 23/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 5.8531 - g2_mse: 5.7972 - g3_mse: 7.6366 - loss: 19.2869
Epoch 24/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - g1_mse: 5.8902 - g2_mse: 6.1089 - g3_mse: 6.4807 - loss: 18.4798
Epoch 25/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 5.3514 - g2_mse: 5.4275 - g3_mse: 7.5045 - loss: 18.2834
Epoch 26/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 5.5724 - g2_mse: 5.6859 - g3_mse: 7.8207 - loss: 19.0790
Epoch 27/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 5.0057 - g2_mse: 5.4838 - g3_mse: 7.7941 - loss: 18.2836
Epoch 28/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.6938 - g2_mse: 5.6121 - g3_mse: 6.9462 - loss: 17.2521
Epoch 29/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 5.1858 - g2_mse: 5.4510 - g3_mse: 6.5872 - loss: 17.2240
Epoch 30/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 5.1213 - g2_mse: 5.1595 - g3_mse: 6.4706 - loss: 16.7515
Epoch 31/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.8644 - g2_mse: 5.3376 - g3_mse: 6.1779 - loss: 16.3799
Epoch 32/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.9803 - g2_mse: 5.8748 - g3_mse: 6.5815 - loss: 17.4366
Epoch 33/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 5.0379 - g2_mse: 5.7357 - g3_mse: 6.6898 - loss: 17.4634
Epoch 34/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.7628 - g2_mse: 5.1371 - g3_mse: 6.0370 - loss: 15.9369
Epoch 35/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.6850 - g2_mse: 4.8246 - g3_mse: 6.1500 - loss: 15.6596
Epoch 36/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5733 - g2_mse: 5.4410 - g3_mse: 6.2322 - loss: 16.2465
Epoch 37/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.8703 - g2_mse: 4.7496 - g3_mse: 5.9036 - loss: 15.5235
Epoch 38/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.4791 - g2_mse: 4.8759 - g3_mse: 6.1666 - loss: 15.5217
Epoch 39/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.8290 - g2_mse: 5.2150 - g3_mse: 5.8873 - loss: 15.9313
Epoch 40/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3653 - g2_mse: 4.8859 - g3_mse: 6.3750 - loss: 15.6261
Epoch 41/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.6353 - g2_mse: 5.9770 - g3_mse: 7.1430 - loss: 17.7553
Epoch 42/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 5.2568 - g2_mse: 4.9453 - g3_mse: 6.7135 - loss: 16.9156
Epoch 43/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.4600 - g2_mse: 4.4856 - g3_mse: 5.5654 - loss: 14.5110
Epoch 44/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.6953 - g2_mse: 4.8937 - g3_mse: 5.9529 - loss: 15.5419
Epoch 45/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.4902 - g2_mse: 4.5064 - g3_mse: 6.0175 - loss: 15.0141
Epoch 46/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.7687 - g2_mse: 5.1289 - g3_mse: 6.4419 - loss: 16.3395
Epoch 47/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5379 - g2_mse: 4.7211 - g3_mse: 6.4025 - loss: 15.6614
Epoch 48/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 5.1368 - g2_mse: 4.7277 - g3_mse: 5.7923 - loss: 15.6569
Epoch 49/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5661 - g2_mse: 5.2979 - g3_mse: 6.3637 - loss: 16.2277
Epoch 50/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5762 - g2_mse: 5.1934 - g3_mse: 6.1625 - loss: 15.9321
Epoch 51/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.7158 - g2_mse: 5.1923 - g3_mse: 7.1540 - loss: 17.0620
Epoch 52/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.6274 - g2_mse: 4.9853 - g3_mse: 6.3819 - loss: 15.9945
Epoch 53/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5343 - g2_mse: 5.1525 - g3_mse: 6.2628 - loss: 15.9496
Epoch 54/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0458 - g2_mse: 4.4559 - g3_mse: 5.6570 - loss: 14.1586
Epoch 55/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3078 - g2_mse: 4.8058 - g3_mse: 6.3588 - loss: 15.4724
Epoch 56/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3339 - g2_mse: 4.9287 - g3_mse: 6.5464 - loss: 15.8089
Epoch 57/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3953 - g2_mse: 4.7647 - g3_mse: 5.9492 - loss: 15.1092
Epoch 58/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.2831 - g2_mse: 5.1637 - g3_mse: 6.3175 - loss: 15.7643
Epoch 59/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5694 - g2_mse: 5.0483 - g3_mse: 6.5484 - loss: 16.1660
Epoch 60/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.6736 - g2_mse: 5.3273 - g3_mse: 7.1237 - loss: 17.1246
Epoch 61/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.1874 - g2_mse: 4.7728 - g3_mse: 5.8422 - loss: 14.8024
Epoch 62/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.9660 - g2_mse: 4.5953 - g3_mse: 6.1959 - loss: 15.7571
Epoch 63/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.7006 - g2_mse: 4.8077 - g3_mse: 5.4654 - loss: 14.9738
Epoch 64/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0662 - g2_mse: 4.7354 - g3_mse: 5.4516 - loss: 14.2532
Epoch 65/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - g1_mse: 4.2191 - g2_mse: 4.4812 - g3_mse: 6.3722 - loss: 15.0725
Epoch 66/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.9778 - g2_mse: 5.0630 - g3_mse: 5.9568 - loss: 15.9976
Epoch 67/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3968 - g2_mse: 5.0350 - g3_mse: 6.2865 - loss: 15.7183
Epoch 68/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.2705 - g2_mse: 4.9361 - g3_mse: 6.0015 - loss: 15.2081
Epoch 69/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.2922 - g2_mse: 4.8376 - g3_mse: 6.4545 - loss: 15.5842
Epoch 70/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.4595 - g2_mse: 4.7499 - g3_mse: 5.8024 - loss: 15.0118
Epoch 71/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0016 - g2_mse: 4.8535 - g3_mse: 5.9712 - loss: 14.8263
Epoch 72/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 4.1881 - g2_mse: 5.1895 - g3_mse: 5.8156 - loss: 15.1932
Epoch 73/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.1151 - g2_mse: 5.3487 - g3_mse: 5.8390 - loss: 15.3029
Epoch 74/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - g1_mse: 5.0062 - g2_mse: 4.7627 - g3_mse: 6.4752 - loss: 16.2442
Epoch 75/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - g1_mse: 4.2720 - g2_mse: 4.4196 - g3_mse: 5.3240 - loss: 14.0155
Epoch 76/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3814 - g2_mse: 4.4725 - g3_mse: 5.6488 - loss: 14.5027
Epoch 77/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5307 - g2_mse: 4.8948 - g3_mse: 5.8068 - loss: 15.2323
Epoch 78/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8634 - g2_mse: 4.2558 - g3_mse: 5.5530 - loss: 13.6723
Epoch 79/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.4918 - g2_mse: 5.5736 - g3_mse: 6.7558 - loss: 16.8211
Epoch 80/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.1049 - g2_mse: 4.8196 - g3_mse: 5.5653 - loss: 14.4897
Epoch 81/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - g1_mse: 4.2900 - g2_mse: 4.1279 - g3_mse: 6.0075 - loss: 14.4254
Epoch 82/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.2848 - g2_mse: 4.7646 - g3_mse: 5.1402 - loss: 14.1896
Epoch 83/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.2073 - g2_mse: 4.6228 - g3_mse: 5.8682 - loss: 14.6983
Epoch 84/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.1730 - g2_mse: 4.9007 - g3_mse: 6.1701 - loss: 15.2438
Epoch 85/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.2536 - g2_mse: 4.5795 - g3_mse: 5.4511 - loss: 14.2842
Epoch 86/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.4405 - g2_mse: 4.8541 - g3_mse: 6.1540 - loss: 15.4485
Epoch 87/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 4.1877 - g2_mse: 4.4420 - g3_mse: 5.4938 - loss: 14.1236
Epoch 88/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0125 - g2_mse: 4.6035 - g3_mse: 5.8423 - loss: 14.4583
Epoch 89/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - g1_mse: 4.0701 - g2_mse: 4.5259 - g3_mse: 5.6526 - loss: 14.2485
Epoch 90/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8161 - g2_mse: 4.6237 - g3_mse: 6.4590 - loss: 14.8989
Epoch 91/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0749 - g2_mse: 4.4840 - g3_mse: 5.3522 - loss: 13.9111
Epoch 92/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0666 - g2_mse: 4.4054 - g3_mse: 5.5479 - loss: 14.0200
Epoch 93/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3486 - g2_mse: 4.9717 - g3_mse: 6.1908 - loss: 15.5111
Epoch 94/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0637 - g2_mse: 4.2622 - g3_mse: 4.7199 - loss: 13.0458
Epoch 95/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - g1_mse: 4.3825 - g2_mse: 4.6726 - g3_mse: 6.0440 - loss: 15.0991
Epoch 96/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.9520 - g2_mse: 4.3575 - g3_mse: 5.7802 - loss: 14.0897
Epoch 97/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8477 - g2_mse: 4.9576 - g3_mse: 6.0658 - loss: 14.8711
Epoch 98/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5852 - g2_mse: 3.6081 - g3_mse: 4.6489 - loss: 11.8422
Epoch 99/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.2668 - g2_mse: 4.4834 - g3_mse: 5.3174 - loss: 14.0676
Epoch 100/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 4.3900 - g2_mse: 5.4587 - g3_mse: 6.7290 - loss: 16.5777
Epoch 101/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 4.1995 - g2_mse: 4.4471 - g3_mse: 5.5746 - loss: 14.2212
Epoch 102/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0140 - g2_mse: 4.8745 - g3_mse: 6.0239 - loss: 14.9124
Epoch 103/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3162 - g2_mse: 4.2930 - g3_mse: 4.9402 - loss: 13.5495
Epoch 104/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - g1_mse: 3.6303 - g2_mse: 4.2274 - g3_mse: 5.1097 - loss: 12.9673
Epoch 105/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - g1_mse: 4.4871 - g2_mse: 4.1865 - g3_mse: 5.7461 - loss: 14.4198
Epoch 106/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - g1_mse: 3.8734 - g2_mse: 4.7437 - g3_mse: 6.1860 - loss: 14.8031
Epoch 107/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8546 - g2_mse: 3.9329 - g3_mse: 5.5210 - loss: 13.3086
Epoch 108/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.9777 - g2_mse: 4.3029 - g3_mse: 5.0712 - loss: 13.3518
Epoch 109/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0066 - g2_mse: 3.9061 - g3_mse: 4.8290 - loss: 12.7417
Epoch 110/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5719 - g2_mse: 4.2876 - g3_mse: 5.9799 - loss: 13.8395
Epoch 111/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.6489 - g2_mse: 4.0018 - g3_mse: 4.8397 - loss: 12.4903
Epoch 112/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3458 - g2_mse: 4.0423 - g3_mse: 5.1566 - loss: 13.5447
Epoch 113/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.7184 - g2_mse: 4.1954 - g3_mse: 5.1247 - loss: 13.0385
Epoch 114/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.7202 - g2_mse: 4.0968 - g3_mse: 4.8708 - loss: 12.6878
Epoch 115/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.1010 - g2_mse: 4.3161 - g3_mse: 5.6580 - loss: 14.0752
Epoch 116/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5839 - g2_mse: 4.3449 - g3_mse: 4.9456 - loss: 12.8743
Epoch 117/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 3.9294 - g2_mse: 4.0193 - g3_mse: 5.0672 - loss: 13.0158
Epoch 118/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.0354 - g2_mse: 3.8718 - g3_mse: 4.4317 - loss: 12.3388
Epoch 119/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - g1_mse: 4.1054 - g2_mse: 4.1811 - g3_mse: 4.9423 - loss: 13.2289
Epoch 120/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8324 - g2_mse: 3.9829 - g3_mse: 4.8010 - loss: 12.6162
Epoch 121/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.6836 - g2_mse: 3.8675 - g3_mse: 5.0105 - loss: 12.5617
Epoch 122/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8976 - g2_mse: 4.0466 - g3_mse: 4.8474 - loss: 12.7916
Epoch 123/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.6658 - g2_mse: 4.3752 - g3_mse: 5.4707 - loss: 13.5117
Epoch 124/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.7364 - g2_mse: 3.8572 - g3_mse: 5.3375 - loss: 12.9311
Epoch 125/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.5312 - g2_mse: 5.0953 - g3_mse: 5.4203 - loss: 15.0468
Epoch 126/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5888 - g2_mse: 3.6538 - g3_mse: 5.2499 - loss: 12.4925
Epoch 127/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - g1_mse: 4.1228 - g2_mse: 4.2877 - g3_mse: 5.2232 - loss: 13.6338
Epoch 128/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 4.1614 - g2_mse: 3.7041 - g3_mse: 4.6002 - loss: 12.4657
Epoch 129/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.6819 - g2_mse: 3.7870 - g3_mse: 4.5859 - loss: 12.0548
Epoch 130/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - g1_mse: 3.6799 - g2_mse: 3.5957 - g3_mse: 4.3908 - loss: 11.6665
Epoch 131/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.6261 - g2_mse: 3.9714 - g3_mse: 5.1238 - loss: 12.7213
Epoch 132/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - g1_mse: 3.7528 - g2_mse: 4.1502 - g3_mse: 4.6334 - loss: 12.5365
Epoch 133/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - g1_mse: 3.6533 - g2_mse: 3.6527 - g3_mse: 5.0958 - loss: 12.4018
Epoch 134/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - g1_mse: 4.0065 - g2_mse: 3.7253 - g3_mse: 5.0253 - loss: 12.7571
Epoch 135/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.9867 - g2_mse: 4.1436 - g3_mse: 4.9559 - loss: 13.0862
Epoch 136/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.4354 - g2_mse: 3.6530 - g3_mse: 4.3401 - loss: 11.4284
Epoch 137/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8122 - g2_mse: 4.0915 - g3_mse: 4.8672 - loss: 12.7709
Epoch 138/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.7921 - g2_mse: 4.0463 - g3_mse: 4.6532 - loss: 12.4915
Epoch 139/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.9020 - g2_mse: 4.0742 - g3_mse: 4.6847 - loss: 12.6609
Epoch 140/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.3306 - g2_mse: 3.8355 - g3_mse: 4.2868 - loss: 12.4528
Epoch 141/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.3995 - g2_mse: 3.2780 - g3_mse: 4.0347 - loss: 10.7121
Epoch 142/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5535 - g2_mse: 3.4395 - g3_mse: 4.0043 - loss: 10.9973
Epoch 143/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 4.1158 - g2_mse: 3.5886 - g3_mse: 4.6763 - loss: 12.3807
Epoch 144/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8866 - g2_mse: 3.7561 - g3_mse: 4.5974 - loss: 12.2401
Epoch 145/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - g1_mse: 3.2930 - g2_mse: 3.5735 - g3_mse: 4.0915 - loss: 10.9580
Epoch 146/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.4754 - g2_mse: 3.7839 - g3_mse: 4.4576 - loss: 11.7170
Epoch 147/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - g1_mse: 3.8000 - g2_mse: 3.8100 - g3_mse: 4.4286 - loss: 12.0386
Epoch 148/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5788 - g2_mse: 3.8428 - g3_mse: 4.6243 - loss: 12.0459
Epoch 149/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5408 - g2_mse: 3.4486 - g3_mse: 4.3955 - loss: 11.3849
Epoch 150/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8289 - g2_mse: 3.5524 - g3_mse: 4.0417 - loss: 11.4230
Epoch 151/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8171 - g2_mse: 4.0181 - g3_mse: 4.6748 - loss: 12.5100
Epoch 152/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5660 - g2_mse: 3.3951 - g3_mse: 4.3179 - loss: 11.2790
Epoch 153/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - g1_mse: 3.7911 - g2_mse: 3.7469 - g3_mse: 4.1699 - loss: 11.7079
Epoch 154/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.3043 - g2_mse: 3.8798 - g3_mse: 4.7211 - loss: 11.9052
Epoch 155/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.3926 - g2_mse: 3.6451 - g3_mse: 4.1689 - loss: 11.2067
Epoch 156/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - g1_mse: 3.3123 - g2_mse: 3.4782 - g3_mse: 4.0229 - loss: 10.8134
Epoch 157/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - g1_mse: 3.4924 - g2_mse: 3.3168 - g3_mse: 3.7033 - loss: 10.5124
Epoch 158/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - g1_mse: 3.2163 - g2_mse: 3.6604 - g3_mse: 3.8065 - loss: 10.6832
Epoch 159/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.2415 - g2_mse: 3.3032 - g3_mse: 4.0306 - loss: 10.5752
Epoch 160/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.8115 - g2_mse: 3.6997 - g3_mse: 4.1007 - loss: 11.6118
Epoch 161/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - g1_mse: 3.6109 - g2_mse: 3.1931 - g3_mse: 4.1186 - loss: 10.9226
Epoch 162/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.2008 - g2_mse: 3.0834 - g3_mse: 3.8422 - loss: 10.1265
Epoch 163/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.5484 - g2_mse: 3.5464 - g3_mse: 4.0110 - loss: 11.1058
Epoch 164/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.6503 - g2_mse: 3.4316 - g3_mse: 3.9663 - loss: 11.0482
Epoch 165/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.2971 - g2_mse: 3.7014 - g3_mse: 3.7587 - loss: 10.7573
Epoch 166/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 3.0013 - g2_mse: 3.1963 - g3_mse: 4.0219 - loss: 10.2195
Epoch 167/500

In [336]:
model.summary()

Model: "functional_64"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_47      │ (None, 56)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_g1 (Dense)    │ (None, 32)        │      1,824 │ input_layer_47[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ g1 (Dense)          │ (None, 1)         │         33 │ dense_g1[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concat_g2           │ (None, 57)        │          0 │ input_layer_47[0… │
│ (Concatenate)       │                   │            │ g1[0][0]          │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_g2 (Dense)    │ (None, 32)        │      1,856 │ concat_g2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ g2 (Dense)          │ (None, 1)         │         33 │ dense_g2[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concat_g3           │ (None, 58)        │          0 │ input_layer_47[0… │
│ (Concatenate)       │                   │            │ g1[0][0],         │
│                     │                   │            │ g2[0][0]          │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_g3 (Dense)    │ (None, 32)        │      1,888 │ concat_g3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ g3 (Dense)          │ (None, 1)         │         33 │ dense_g3[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,003 (66.42 KB)

 Trainable params: 5,667 (22.14 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 11,336 (44.29 KB)

In [337]:
model.evaluate(x_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - g1_mse: 9.9989 - g2_mse: 0.0000e+00 - g3_mse: 0.0000e+00 - loss: 9.9989

[10.217089653015137, 10.217089653015137, 0.0, 0.0]

In [343]:
pred = model.predict(x_train)
pred = np.clip(pred, 0, 20).astype(int) # обрезка
pd.DataFrame(pred.reshape(519, 3)) # преобразуем в двухмерный массив

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step

      0   1   2
0    16  11  13
1    12   8   9
2     7   8   5
3    10  10  12
4    10  10   8
..   ..  ..  ..
514  12  14  13
515  12  13  15
516  10  13  12
517  13  10  11
518  14   9  12

[519 rows x 3 columns]

In [342]:
pd.DataFrame(data_y)

     G1  G2  G3
0     0  11  11
1     9  11  11
2    12  13  12
3    14  14  14
4    11  13  13
..   ..  ..  ..
644  10  11  10
645  15  15  16
646  11  12   9
647  10  10  10
648  10  11  11

[649 rows x 3 columns]