Deep Lerning. We will search G1, G2 and after G3.

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, Concatenate
from tensorflow.keras import regularizers
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

In [22]:
student_performance = fetch_ucirepo(id=320) 

data_X = student_performance.data.features
data_y = student_performance.data.targets

X = pd.get_dummies(data_X)
y = data_y

# При использовании pd.get_dummies для преобразования категориальных признаков в dummy-переменные, нет необходимости в явном использовании слоя нормализации в модели. 
# Это потому, что pd.get_dummies создает бинарные (или dummy) переменные, которые по своей природе уже нормализованы (их значения находятся в диапазоне [0, 1]).
# слой Flatten так же не нужен

In [23]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
x_train = x_train.astype(float)
x_test = x_test.astype(float)

y_train = y_train.astype(float)
y_test = y_test.astype(float)

In [25]:
input_scores = Input(shape=(x_train.shape[1],))

# Слои для предсказания g1
dense_g1 = Dense(16, activation="relu", kernel_regularizer=regularizers.l2(0.001))(input_scores)
output_g1 = Dense(1)(dense_g1)

# Слои для предсказания g2 (используя input_scores и g1)
concat_g2 = Concatenate()([input_scores, output_g1])
dense_g2 = Dense(16, activation="relu", kernel_regularizer=regularizers.l2(0.001))(concat_g2)
output_g2 = Dense(1)(dense_g2)
# Слои для предсказания g3 (используя input_scores, g1 и g2)
concat_g3 = Concatenate()([input_scores, output_g1, output_g2])
dense_g3 = Dense(16, activation="relu", kernel_regularizer=regularizers.l2(0.001))(concat_g3)
output_g3 = Dense(1)(dense_g3)

model = Model(inputs=input_scores, outputs=[output_g1, output_g2, output_g3])

In [26]:
model.compile(optimizer="adam", loss="mse", metrics=["mse", "mse", "mse"])

In [27]:
model.fit(x_train, [y_train['G1'], y_train['G2'], y_train['G3']], epochs=300)

Epoch 1/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - dense_17_mse: 194.9570 - dense_19_mse: 267.7523 - dense_21_mse: 143.5664 - loss: 606.3494
Epoch 2/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 125.4847 - dense_19_mse: 201.9771 - dense_21_mse: 94.2136 - loss: 421.7451
Epoch 3/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 71.2384 - dense_19_mse: 151.8272 - dense_21_mse: 55.6907 - loss: 278.8241
Epoch 4/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_17_mse: 38.2798 - dense_19_mse: 101.4657 - dense_21_mse: 28.1093 - loss: 167.9217
Epoch 5/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - dense_17_mse: 20.3907 - dense_19_mse: 58.7612 - dense_21_mse: 16.9470 - loss: 96.1656
Epoch 6/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - dense_17_mse: 12.2812 - dense_19_mse: 31.6237 - dense_21_mse: 13.3555 - loss: 57.3269
Epoch 7/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - dense_17_mse: 10.4533 - dense_19_mse: 18.6000 - dense_21_mse: 11.3409 - loss: 40.4603
Epoch 8/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 9.5587 - dense_19_mse: 14.4278 - dense_21_mse: 11.8507 - loss: 35.9028
Epoch 9/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 9.2902 - dense_19_mse: 12.2806 - dense_21_mse: 11.5558 - loss: 33.1916
Epoch 10/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 10.9623 - dense_19_mse: 13.5968 - dense_21_mse: 10.7707 - loss: 35.3942
Epoch 11/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 9.2054 - dense_19_mse: 10.5369 - dense_21_mse: 8.9144 - loss: 28.7208
Epoch 12/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 9.6192 - dense_19_mse: 11.6717 - dense_21_mse: 11.0072 - loss: 32.3619
Epoch 13/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 8.7092 - dense_19_mse: 10.2724 - dense_21_mse: 9.6251 - loss: 28.6704
Epoch 14/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 7.9585 - dense_19_mse: 9.3838 - dense_21_mse: 7.9018 - loss: 25.3078
Epoch 15/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 8.6210 - dense_19_mse: 9.5968 - dense_21_mse: 9.1431 - loss: 27.4248
Epoch 16/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 7.7764 - dense_19_mse: 7.9622 - dense_21_mse: 7.6092 - loss: 23.4116
Epoch 17/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 7.4716 - dense_19_mse: 8.7395 - dense_21_mse: 9.0349 - loss: 25.3102
Epoch 18/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - dense_17_mse: 7.1901 - dense_19_mse: 8.9098 - dense_21_mse: 9.0637 - loss: 25.2280
Epoch 19/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 6.6917 - dense_19_mse: 7.2561 - dense_21_mse: 7.6561 - loss: 21.6686
Epoch 20/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 6.6579 - dense_19_mse: 7.1356 - dense_21_mse: 7.5487 - loss: 21.4071
Epoch 21/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 6.9169 - dense_19_mse: 6.8882 - dense_21_mse: 7.0135 - loss: 20.8839
Epoch 22/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 7.2324 - dense_19_mse: 7.6382 - dense_21_mse: 8.3808 - loss: 23.3172
Epoch 23/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 6.3529 - dense_19_mse: 6.5640 - dense_21_mse: 7.0155 - loss: 19.9985
Epoch 24/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 6.5411 - dense_19_mse: 6.4460 - dense_21_mse: 7.1661 - loss: 20.2196
Epoch 25/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.8548 - dense_19_mse: 6.4384 - dense_21_mse: 6.6289 - loss: 18.9889
Epoch 26/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - dense_17_mse: 5.5969 - dense_19_mse: 6.0134 - dense_21_mse: 6.7510 - loss: 18.4285
Epoch 27/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - dense_17_mse: 6.9956 - dense_19_mse: 7.4239 - dense_21_mse: 8.9847 - loss: 23.4718
Epoch 28/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 6.1150 - dense_19_mse: 6.7330 - dense_21_mse: 7.8843 - loss: 20.8002
Epoch 29/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - dense_17_mse: 5.6293 - dense_19_mse: 6.4879 - dense_21_mse: 7.7630 - loss: 19.9486
Epoch 30/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.0526 - dense_19_mse: 5.5403 - dense_21_mse: 6.9213 - loss: 17.5828
Epoch 31/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.5874 - dense_19_mse: 6.5094 - dense_21_mse: 7.6808 - loss: 19.8466
Epoch 32/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.8819 - dense_19_mse: 6.0006 - dense_21_mse: 7.0486 - loss: 18.0004
Epoch 33/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.3060 - dense_19_mse: 6.1560 - dense_21_mse: 6.9981 - loss: 18.5297
Epoch 34/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.2484 - dense_19_mse: 5.8373 - dense_21_mse: 7.5868 - loss: 18.7424
Epoch 35/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 773us/step - dense_17_mse: 5.2668 - dense_19_mse: 5.6583 - dense_21_mse: 8.2862 - loss: 19.2816
Epoch 36/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - dense_17_mse: 5.3652 - dense_19_mse: 5.2512 - dense_21_mse: 6.3024 - loss: 16.9893
Epoch 37/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.9271 - dense_19_mse: 5.6596 - dense_21_mse: 7.5169 - loss: 18.1743
Epoch 38/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5067 - dense_19_mse: 5.4608 - dense_21_mse: 6.1041 - loss: 16.1426
Epoch 39/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_17_mse: 4.6251 - dense_19_mse: 5.3750 - dense_21_mse: 6.4704 - loss: 16.5418
Epoch 40/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - dense_17_mse: 4.6873 - dense_19_mse: 5.1105 - dense_21_mse: 6.5585 - loss: 16.4278
Epoch 41/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.4870 - dense_19_mse: 6.3490 - dense_21_mse: 7.0196 - loss: 18.9272
Epoch 42/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.8888 - dense_19_mse: 5.1174 - dense_21_mse: 6.1656 - loss: 16.2439
Epoch 43/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.7623 - dense_19_mse: 5.4654 - dense_21_mse: 6.7423 - loss: 17.0422
Epoch 44/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3221 - dense_19_mse: 4.6906 - dense_21_mse: 6.0815 - loss: 15.1667
Epoch 45/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5848 - dense_19_mse: 5.3673 - dense_21_mse: 6.6777 - loss: 16.7026
Epoch 46/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - dense_17_mse: 4.3079 - dense_19_mse: 4.6824 - dense_21_mse: 6.0016 - loss: 15.0648
Epoch 47/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4732 - dense_19_mse: 5.1197 - dense_21_mse: 5.5499 - loss: 15.2161
Epoch 48/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.6492 - dense_19_mse: 5.3919 - dense_21_mse: 6.3153 - loss: 16.4299
Epoch 49/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - dense_17_mse: 4.7913 - dense_19_mse: 4.9756 - dense_21_mse: 5.7982 - loss: 15.6386
Epoch 50/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.6339 - dense_19_mse: 5.6582 - dense_21_mse: 7.2238 - loss: 17.5896
Epoch 51/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.2306 - dense_19_mse: 5.8709 - dense_21_mse: 7.8838 - loss: 19.0593
Epoch 52/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5047 - dense_19_mse: 5.4897 - dense_21_mse: 7.7653 - loss: 17.8339
Epoch 53/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - dense_17_mse: 4.2954 - dense_19_mse: 5.0350 - dense_21_mse: 6.1852 - loss: 15.5900
Epoch 54/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.8361 - dense_19_mse: 4.9451 - dense_21_mse: 6.2966 - loss: 16.1524
Epoch 55/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - dense_17_mse: 5.0401 - dense_19_mse: 5.1841 - dense_21_mse: 6.2600 - loss: 16.5588
Epoch 56/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.6371 - dense_19_mse: 5.2166 - dense_21_mse: 6.7989 - loss: 16.7275
Epoch 57/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 5.0576 - dense_19_mse: 5.5163 - dense_21_mse: 6.3638 - loss: 17.0130
Epoch 58/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3012 - dense_19_mse: 5.4402 - dense_21_mse: 7.0937 - loss: 16.9105
Epoch 59/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.7210 - dense_19_mse: 4.8621 - dense_21_mse: 6.2125 - loss: 15.8712
Epoch 60/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.7414 - dense_19_mse: 5.6356 - dense_21_mse: 6.4469 - loss: 16.8995
Epoch 61/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4397 - dense_19_mse: 5.4869 - dense_21_mse: 6.4862 - loss: 16.4886
Epoch 62/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2817 - dense_19_mse: 4.7060 - dense_21_mse: 6.2793 - loss: 15.3431
Epoch 63/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3563 - dense_19_mse: 5.0982 - dense_21_mse: 5.6939 - loss: 15.2247
Epoch 64/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - dense_17_mse: 4.4773 - dense_19_mse: 5.2225 - dense_21_mse: 6.7772 - loss: 16.5535
Epoch 65/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5114 - dense_19_mse: 5.4437 - dense_21_mse: 6.7373 - loss: 16.7691
Epoch 66/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3898 - dense_19_mse: 5.0795 - dense_21_mse: 6.5225 - loss: 16.0686
Epoch 67/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4574 - dense_19_mse: 4.7138 - dense_21_mse: 5.7538 - loss: 15.0019
Epoch 68/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 774us/step - dense_17_mse: 4.5505 - dense_19_mse: 5.2959 - dense_21_mse: 6.8167 - loss: 16.7402
Epoch 69/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3919 - dense_19_mse: 5.1238 - dense_21_mse: 6.1355 - loss: 15.7285
Epoch 70/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.7253 - dense_19_mse: 5.2427 - dense_21_mse: 6.2849 - loss: 16.3304
Epoch 71/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.7974 - dense_19_mse: 4.6393 - dense_21_mse: 5.6950 - loss: 15.2093
Epoch 72/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.6081 - dense_19_mse: 4.9536 - dense_21_mse: 5.8886 - loss: 15.5280
Epoch 73/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.0936 - dense_19_mse: 5.2474 - dense_21_mse: 6.3433 - loss: 15.7622
Epoch 74/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2688 - dense_19_mse: 4.6674 - dense_21_mse: 6.3870 - loss: 15.4014
Epoch 75/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - dense_17_mse: 4.3404 - dense_19_mse: 4.6494 - dense_21_mse: 6.5344 - loss: 15.6025
Epoch 76/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2739 - dense_19_mse: 4.7196 - dense_21_mse: 6.7223 - loss: 15.7942
Epoch 77/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_17_mse: 4.3222 - dense_19_mse: 5.1824 - dense_21_mse: 6.8225 - loss: 16.4058
Epoch 78/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4644 - dense_19_mse: 5.0544 - dense_21_mse: 6.3307 - loss: 15.9282
Epoch 79/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.0553 - dense_19_mse: 5.1980 - dense_21_mse: 6.5532 - loss: 15.8854
Epoch 80/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - dense_17_mse: 4.3497 - dense_19_mse: 4.7938 - dense_21_mse: 6.3082 - loss: 15.5309
Epoch 81/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.8489 - dense_19_mse: 4.4072 - dense_21_mse: 5.3631 - loss: 13.6985
Epoch 82/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.8190 - dense_19_mse: 4.3478 - dense_21_mse: 6.2264 - loss: 14.4726
Epoch 83/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - dense_17_mse: 4.4371 - dense_19_mse: 5.2378 - dense_21_mse: 6.9929 - loss: 16.7473
Epoch 84/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.9669 - dense_19_mse: 4.3717 - dense_21_mse: 5.3064 - loss: 13.7246
Epoch 85/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1555 - dense_19_mse: 4.8207 - dense_21_mse: 6.5389 - loss: 15.5948
Epoch 86/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4161 - dense_19_mse: 4.6383 - dense_21_mse: 5.7968 - loss: 14.9312
Epoch 87/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4346 - dense_19_mse: 5.1306 - dense_21_mse: 6.2196 - loss: 15.8650
Epoch 88/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.0326 - dense_19_mse: 4.4535 - dense_21_mse: 6.1060 - loss: 14.6723
Epoch 89/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4432 - dense_19_mse: 5.2228 - dense_21_mse: 6.2261 - loss: 15.9726
Epoch 90/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.7532 - dense_19_mse: 5.1364 - dense_21_mse: 6.5587 - loss: 16.5289
Epoch 91/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5050 - dense_19_mse: 4.7808 - dense_21_mse: 5.5664 - loss: 14.9330
Epoch 92/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5166 - dense_19_mse: 4.7524 - dense_21_mse: 6.3735 - loss: 15.7233
Epoch 93/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - dense_17_mse: 4.0020 - dense_19_mse: 4.6287 - dense_21_mse: 5.9104 - loss: 14.6220
Epoch 94/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1425 - dense_19_mse: 4.8620 - dense_21_mse: 6.5363 - loss: 15.6219
Epoch 95/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.9968 - dense_19_mse: 4.6558 - dense_21_mse: 5.9624 - loss: 14.6963
Epoch 96/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2943 - dense_19_mse: 4.6792 - dense_21_mse: 5.5868 - loss: 14.6416
Epoch 97/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - dense_17_mse: 4.0180 - dense_19_mse: 4.3350 - dense_21_mse: 6.1759 - loss: 14.6104
Epoch 98/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.6770 - dense_19_mse: 4.3988 - dense_21_mse: 5.6979 - loss: 14.8553
Epoch 99/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5037 - dense_19_mse: 5.0457 - dense_21_mse: 6.2629 - loss: 15.8940
Epoch 100/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.0262 - dense_19_mse: 4.7106 - dense_21_mse: 6.4058 - loss: 15.2247
Epoch 101/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_17_mse: 4.1186 - dense_19_mse: 4.3786 - dense_21_mse: 6.1616 - loss: 14.7408
Epoch 102/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3567 - dense_19_mse: 4.5681 - dense_21_mse: 5.9892 - loss: 14.9962
Epoch 103/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2605 - dense_19_mse: 4.7081 - dense_21_mse: 6.5332 - loss: 15.5840
Epoch 104/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5135 - dense_19_mse: 4.8795 - dense_21_mse: 6.4375 - loss: 15.9129
Epoch 105/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.9774 - dense_19_mse: 4.8050 - dense_21_mse: 6.1561 - loss: 15.0212
Epoch 106/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - dense_17_mse: 4.0121 - dense_19_mse: 4.7250 - dense_21_mse: 6.5255 - loss: 15.3456
Epoch 107/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.6669 - dense_19_mse: 5.2783 - dense_21_mse: 6.5109 - loss: 16.5392
Epoch 108/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.9622 - dense_19_mse: 4.5919 - dense_21_mse: 5.5305 - loss: 14.1679
Epoch 109/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2659 - dense_19_mse: 4.4902 - dense_21_mse: 5.7608 - loss: 14.6003
Epoch 110/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3677 - dense_19_mse: 4.3592 - dense_21_mse: 5.8022 - loss: 14.6127
Epoch 111/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.9091 - dense_19_mse: 4.2912 - dense_21_mse: 5.3982 - loss: 13.6820
Epoch 112/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3952 - dense_19_mse: 4.6876 - dense_21_mse: 6.0168 - loss: 15.1836
Epoch 113/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.8646 - dense_19_mse: 4.4094 - dense_21_mse: 5.6440 - loss: 14.0020
Epoch 114/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - dense_17_mse: 4.0891 - dense_19_mse: 4.7097 - dense_21_mse: 6.3947 - loss: 15.2777
Epoch 115/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4612 - dense_19_mse: 4.8757 - dense_21_mse: 6.4505 - loss: 15.8718
Epoch 116/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2834 - dense_19_mse: 4.9146 - dense_21_mse: 6.3646 - loss: 15.6469
Epoch 117/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.0497 - dense_19_mse: 4.5649 - dense_21_mse: 5.7660 - loss: 14.4652
Epoch 118/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1235 - dense_19_mse: 4.4121 - dense_21_mse: 5.6164 - loss: 14.2366
Epoch 119/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2054 - dense_19_mse: 4.0029 - dense_21_mse: 4.9091 - loss: 13.2021
Epoch 120/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1412 - dense_19_mse: 4.1328 - dense_21_mse: 5.1910 - loss: 13.5498
Epoch 121/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.3738 - dense_19_mse: 5.4225 - dense_21_mse: 6.8823 - loss: 16.7636
Epoch 122/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.9134 - dense_19_mse: 4.3927 - dense_21_mse: 5.7540 - loss: 14.1452
Epoch 123/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.6638 - dense_19_mse: 4.8547 - dense_21_mse: 5.8955 - loss: 15.4991
Epoch 124/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - dense_17_mse: 3.7555 - dense_19_mse: 4.0925 - dense_21_mse: 5.4125 - loss: 13.3459
Epoch 125/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - dense_17_mse: 4.0489 - dense_19_mse: 4.6991 - dense_21_mse: 5.8311 - loss: 14.6644
Epoch 126/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1524 - dense_19_mse: 4.9033 - dense_21_mse: 6.4858 - loss: 15.6271
Epoch 127/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.8298 - dense_19_mse: 3.7200 - dense_21_mse: 5.2541 - loss: 12.8898
Epoch 128/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_17_mse: 4.3520 - dense_19_mse: 4.4759 - dense_21_mse: 5.7963 - loss: 14.7100
Epoch 129/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - dense_17_mse: 4.1690 - dense_19_mse: 4.3607 - dense_21_mse: 6.1780 - loss: 14.7936
Epoch 130/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - dense_17_mse: 4.3332 - dense_19_mse: 4.5855 - dense_21_mse: 5.4893 - loss: 14.4942
Epoch 131/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.4578 - dense_19_mse: 4.6109 - dense_21_mse: 5.6005 - loss: 14.7554
Epoch 132/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.0515 - dense_19_mse: 4.8996 - dense_21_mse: 5.9857 - loss: 15.0232
Epoch 133/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - dense_17_mse: 3.9443 - dense_19_mse: 4.4049 - dense_21_mse: 5.9440 - loss: 14.3797
Epoch 134/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.7261 - dense_19_mse: 4.7731 - dense_21_mse: 6.3105 - loss: 15.8965
Epoch 135/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.8829 - dense_19_mse: 4.8979 - dense_21_mse: 6.1753 - loss: 15.0429
Epoch 136/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.5002 - dense_19_mse: 4.6751 - dense_21_mse: 6.2382 - loss: 15.5005
Epoch 137/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - dense_17_mse: 4.3631 - dense_19_mse: 3.9568 - dense_21_mse: 5.2861 - loss: 13.6934
Epoch 138/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1275 - dense_19_mse: 4.1302 - dense_21_mse: 5.3519 - loss: 13.6968
Epoch 139/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1223 - dense_19_mse: 4.9190 - dense_21_mse: 6.2299 - loss: 15.3587
Epoch 140/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 3.9384 - dense_19_mse: 4.1329 - dense_21_mse: 5.7316 - loss: 13.8904
Epoch 141/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.2716 - dense_19_mse: 4.5408 - dense_21_mse: 5.8489 - loss: 14.7489
Epoch 142/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 4.1250 - dense_19_mse: 4.2433 - dense_21_mse: 5.5210 - loss: 13.9772
Epoch 143/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_17_mse: 3.7451 - dense_19_mse: 4.0753 - dense_21_mse: 5.7967 - loss: 13.7050
Epoch 144/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - dense_17_mse: 3.9317 - dense_19_mse: 4.4661 - dense_21_mse: 5.7214 - loss: 14.2073
Epoch 145/200

In [28]:
model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 56)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_16 (Dense)    │ (None, 16)        │        912 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_17 (Dense)    │ (None, 1)         │         17 │ dense_16[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_5       │ (None, 57)        │          0 │ input_layer_3[0]… │
│ (Concatenate)       │                   │            │ dense_17[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_18 (Dense)    │ (None, 16)        │        928 │ concatenate_5[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_19 (Dense)    │ (None, 1)         │         17 │ dense_18[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_6       │ (None, 58)        │          0 │ input_layer_3[0]… │
│ (Concatenate)       │                   │            │ dense_17[0][0],   │
│                     │                   │            │ dense_19[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_20 (Dense)    │ (None, 16)        │        944 │ concatenate_6[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_21 (Dense)    │ (None, 1)         │         17 │ dense_20[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 8,507 (33.23 KB)

 Trainable params: 2,835 (11.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,672 (22.16 KB)

In [29]:
model.evaluate(x_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_17_mse: 6.9252 - dense_19_mse: 0.0000e+00 - dense_21_mse: 0.0000e+00 - loss: 7.0227

[7.591578483581543, 7.494076251983643, 0.0, 0.0]

In [30]:
pred = model.predict(x_train)
pred = np.clip(pred, 0, 20).astype(int) # обрезка
pd.DataFrame(pred.reshape(519, 3)) # преобразуем в двухмерный массив

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

      0   1   2
0    13  11  13
1    11   8   9
2     7   9  10
3    13  12  13
4    12  11  10
..   ..  ..  ..
514  13  14  15
515  13  12  15
516   8  14  11
517  14  13  12
518  13  11  13

[519 rows x 3 columns]

In [31]:
pd.DataFrame(data_y)

     G1  G2  G3
0     0  11  11
1     9  11  11
2    12  13  12
3    14  14  14
4    11  13  13
..   ..  ..  ..
644  10  11  10
645  15  15  16
646  11  12   9
647  10  10  10
648  10  11  11

[649 rows x 3 columns]