Deep Lerning. We will search G1, G2 and after G3.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, Dropout, Concatenate
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

In [2]:
student_performance = fetch_ucirepo(id=320) 

data_X = student_performance.data.features
data_y = student_performance.data.targets

X = pd.get_dummies(data_X)
y = data_y


# При использовании pd.get_dummies для преобразования категориальных признаков в dummy-переменные, нет необходимости в явном использовании слоя нормализации в модели. 
# Это потому, что pd.get_dummies создает бинарные (или dummy) переменные, которые по своей природе уже нормализованы (их значения находятся в диапазоне [0, 1]).
# слой Flatten так же не нужен

In [3]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
x_train = x_train.astype(float)
x_test = x_test.astype(float)

y_train = y_train.astype(float)
y_test = y_test.astype(float)

In [5]:
input_scores = Input(shape=(x_train.shape[1],))

# Слои для предсказания g1
dense_g1 = Dense(32, activation="relu")(input_scores)
output_g1 = Dense(1)(dense_g1)

# Слои для предсказания g2 (используя input_scores и g1)
concat_g2 = Concatenate()([input_scores, output_g1])
dense_g2 = Dense(32, activation="relu")(concat_g2)
output_g2 = Dense(1)(dense_g2)

# Слои для предсказания g3 (используя input_scores, g1 и g2)
concat_g3 = Concatenate()([input_scores, output_g1, output_g2])
dense_g3 = Dense(32, activation="relu")(concat_g3)
output_g3 = Dense(1)(dense_g3)

model = Model(inputs=input_scores, outputs=[output_g1, output_g2, output_g3])

In [6]:
model.compile(optimizer="adam", loss="mse", metrics=["mse", "mse", "mse"])

In [7]:
model.fit(x_train, [y_train['G1'], y_train['G2'], y_train['G3']], epochs=500)

Epoch 1/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - dense_1_mse: 38.2770 - dense_3_mse: 66.9738 - dense_5_mse: 253.0183 - loss: 358.2691
Epoch 2/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 10.1278 - dense_3_mse: 19.0541 - dense_5_mse: 126.3625 - loss: 155.5445
Epoch 3/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 9.6621 - dense_3_mse: 10.5745 - dense_5_mse: 39.6692 - loss: 59.9059
Epoch 4/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - dense_1_mse: 7.8882 - dense_3_mse: 10.3753 - dense_5_mse: 14.2180 - loss: 32.4815
Epoch 5/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - dense_1_mse: 6.6997 - dense_3_mse: 7.3065 - dense_5_mse: 9.5243 - loss: 23.5305
Epoch 6/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 7.0477 - dense_3_mse: 7.0185 - dense_5_mse: 9.7381 - loss: 23.8044
Epoch 7/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 6.0518 - dense_3_mse: 6.9603 - dense_5_mse: 9.7351 - loss: 22.7471
Epoch 8/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - dense_1_mse: 6.6615 - dense_3_mse: 7.4164 - dense_5_mse: 9.0487 - loss: 23.1266
Epoch 9/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - dense_1_mse: 6.3376 - dense_3_mse: 6.8866 - dense_5_mse: 10.2437 - loss: 23.4680
Epoch 10/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.4996 - dense_3_mse: 6.3516 - dense_5_mse: 9.0394 - loss: 20.8906
Epoch 11/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.8187 - dense_3_mse: 5.8272 - dense_5_mse: 8.1995 - loss: 18.8455
Epoch 12/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.3633 - dense_3_mse: 6.1758 - dense_5_mse: 9.1587 - loss: 20.6978
Epoch 13/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - dense_1_mse: 5.3523 - dense_3_mse: 6.4595 - dense_5_mse: 9.4195 - loss: 21.2313
Epoch 14/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.9597 - dense_3_mse: 5.6564 - dense_5_mse: 8.5998 - loss: 19.2159
Epoch 15/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - dense_1_mse: 4.7190 - dense_3_mse: 5.2478 - dense_5_mse: 6.9627 - loss: 16.9295
Epoch 16/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.4415 - dense_3_mse: 6.1888 - dense_5_mse: 8.1696 - loss: 19.7999
Epoch 17/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step - dense_1_mse: 4.7457 - dense_3_mse: 5.3242 - dense_5_mse: 7.4149 - loss: 17.4848
Epoch 18/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.7752 - dense_3_mse: 5.4502 - dense_5_mse: 7.3324 - loss: 18.5578
Epoch 19/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.8279 - dense_3_mse: 5.6621 - dense_5_mse: 8.0592 - loss: 18.5492
Epoch 20/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.5100 - dense_3_mse: 5.9903 - dense_5_mse: 7.9384 - loss: 18.4387
Epoch 21/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.4405 - dense_3_mse: 5.7383 - dense_5_mse: 8.1377 - loss: 19.3164
Epoch 22/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - dense_1_mse: 4.8134 - dense_3_mse: 5.4894 - dense_5_mse: 6.9266 - loss: 17.2294
Epoch 23/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3891 - dense_3_mse: 5.1395 - dense_5_mse: 7.8803 - loss: 17.4088
Epoch 24/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2589 - dense_3_mse: 5.0046 - dense_5_mse: 8.2449 - loss: 17.5083
Epoch 25/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.8281 - dense_3_mse: 5.0637 - dense_5_mse: 7.9924 - loss: 17.8841
Epoch 26/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - dense_1_mse: 4.5189 - dense_3_mse: 5.5291 - dense_5_mse: 7.0521 - loss: 17.1000
Epoch 27/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.4680 - dense_3_mse: 5.1707 - dense_5_mse: 8.3679 - loss: 18.0065
Epoch 28/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - dense_1_mse: 4.2448 - dense_3_mse: 4.3515 - dense_5_mse: 5.6631 - loss: 14.2595
Epoch 29/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - dense_1_mse: 4.4349 - dense_3_mse: 4.8052 - dense_5_mse: 6.5303 - loss: 15.7703
Epoch 30/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - dense_1_mse: 4.7441 - dense_3_mse: 5.5434 - dense_5_mse: 6.6820 - loss: 16.9695
Epoch 31/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - dense_1_mse: 4.4198 - dense_3_mse: 5.2894 - dense_5_mse: 6.1398 - loss: 15.8490
Epoch 32/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.9923 - dense_3_mse: 6.0935 - dense_5_mse: 8.2634 - loss: 19.3492
Epoch 33/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - dense_1_mse: 5.1392 - dense_3_mse: 5.8106 - dense_5_mse: 7.4307 - loss: 18.3805
Epoch 34/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - dense_1_mse: 4.5762 - dense_3_mse: 4.7368 - dense_5_mse: 6.3091 - loss: 15.6221
Epoch 35/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - dense_1_mse: 4.6781 - dense_3_mse: 5.5081 - dense_5_mse: 7.5206 - loss: 17.7068
Epoch 36/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2734 - dense_3_mse: 5.1783 - dense_5_mse: 6.5323 - loss: 15.9841
Epoch 37/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.5009 - dense_3_mse: 5.5190 - dense_5_mse: 6.5912 - loss: 16.6111
Epoch 38/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.5587 - dense_3_mse: 4.8607 - dense_5_mse: 6.9602 - loss: 16.3796
Epoch 39/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 5.5521 - dense_3_mse: 5.3758 - dense_5_mse: 7.1742 - loss: 18.1022
Epoch 40/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3992 - dense_3_mse: 4.9802 - dense_5_mse: 6.6583 - loss: 16.0377
Epoch 41/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1318 - dense_3_mse: 4.4736 - dense_5_mse: 6.0145 - loss: 14.6199
Epoch 42/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.6233 - dense_3_mse: 5.8206 - dense_5_mse: 7.2626 - loss: 17.7065
Epoch 43/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3795 - dense_3_mse: 5.1061 - dense_5_mse: 6.5288 - loss: 16.0144
Epoch 44/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.8405 - dense_3_mse: 5.6742 - dense_5_mse: 7.3321 - loss: 17.8468
Epoch 45/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 5.0908 - dense_3_mse: 4.8731 - dense_5_mse: 6.9880 - loss: 16.9519
Epoch 46/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.7800 - dense_3_mse: 5.1906 - dense_5_mse: 7.4263 - loss: 17.3970
Epoch 47/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - dense_1_mse: 4.8162 - dense_3_mse: 5.1533 - dense_5_mse: 6.6210 - loss: 16.5905
Epoch 48/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - dense_1_mse: 4.5867 - dense_3_mse: 5.3315 - dense_5_mse: 6.2246 - loss: 16.1427
Epoch 49/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2507 - dense_3_mse: 5.3003 - dense_5_mse: 6.5973 - loss: 16.1483
Epoch 50/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - dense_1_mse: 4.3749 - dense_3_mse: 4.8111 - dense_5_mse: 6.6186 - loss: 15.8047
Epoch 51/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - dense_1_mse: 4.1206 - dense_3_mse: 4.9218 - dense_5_mse: 6.9512 - loss: 15.9936
Epoch 52/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - dense_1_mse: 4.4227 - dense_3_mse: 4.9295 - dense_5_mse: 6.7068 - loss: 16.0590
Epoch 53/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step - dense_1_mse: 4.1862 - dense_3_mse: 4.2908 - dense_5_mse: 5.3930 - loss: 13.8700
Epoch 54/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1640 - dense_3_mse: 4.4866 - dense_5_mse: 6.1334 - loss: 14.7840
Epoch 55/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.4063 - dense_3_mse: 4.6799 - dense_5_mse: 6.3978 - loss: 15.4840
Epoch 56/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3468 - dense_3_mse: 5.0489 - dense_5_mse: 6.1171 - loss: 15.5128
Epoch 57/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 4.1513 - dense_3_mse: 4.4128 - dense_5_mse: 5.9646 - loss: 14.5288
Epoch 58/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2334 - dense_3_mse: 4.8302 - dense_5_mse: 6.5139 - loss: 15.5775
Epoch 59/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2830 - dense_3_mse: 4.4867 - dense_5_mse: 6.1576 - loss: 14.9273
Epoch 60/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0840 - dense_3_mse: 4.6093 - dense_5_mse: 5.9739 - loss: 14.6673
Epoch 61/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.9635 - dense_3_mse: 4.7880 - dense_5_mse: 6.4695 - loss: 15.2210
Epoch 62/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3197 - dense_3_mse: 5.0288 - dense_5_mse: 6.3241 - loss: 15.6726
Epoch 63/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2324 - dense_3_mse: 4.5486 - dense_5_mse: 6.1075 - loss: 14.8884
Epoch 64/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.2364 - dense_3_mse: 5.1005 - dense_5_mse: 6.9496 - loss: 16.2864
Epoch 65/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6548 - dense_3_mse: 4.0033 - dense_5_mse: 4.8898 - loss: 12.5478
Epoch 66/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0628 - dense_3_mse: 4.5572 - dense_5_mse: 6.2161 - loss: 14.8361
Epoch 67/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0764 - dense_3_mse: 4.5025 - dense_5_mse: 5.6603 - loss: 14.2392
Epoch 68/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - dense_1_mse: 4.3646 - dense_3_mse: 4.3353 - dense_5_mse: 5.7178 - loss: 14.4177
Epoch 69/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - dense_1_mse: 4.1488 - dense_3_mse: 4.9807 - dense_5_mse: 7.0394 - loss: 16.1689
Epoch 70/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - dense_1_mse: 4.1232 - dense_3_mse: 4.6441 - dense_5_mse: 5.7347 - loss: 14.5020
Epoch 71/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - dense_1_mse: 4.0884 - dense_3_mse: 4.5214 - dense_5_mse: 5.7149 - loss: 14.3247
Epoch 72/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - dense_1_mse: 3.7085 - dense_3_mse: 4.8983 - dense_5_mse: 6.6827 - loss: 15.2895
Epoch 73/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - dense_1_mse: 4.2550 - dense_3_mse: 4.7275 - dense_5_mse: 6.3942 - loss: 15.3767
Epoch 74/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - dense_1_mse: 4.0589 - dense_3_mse: 4.2588 - dense_5_mse: 6.7465 - loss: 15.0643
Epoch 75/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - dense_1_mse: 3.8550 - dense_3_mse: 4.3416 - dense_5_mse: 5.2823 - loss: 13.4788
Epoch 76/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - dense_1_mse: 4.1804 - dense_3_mse: 4.3600 - dense_5_mse: 5.6964 - loss: 14.2368
Epoch 77/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.3294 - dense_3_mse: 4.5924 - dense_5_mse: 6.3346 - loss: 15.2564
Epoch 78/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0259 - dense_3_mse: 4.4156 - dense_5_mse: 6.3039 - loss: 14.7454
Epoch 79/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6451 - dense_3_mse: 3.9462 - dense_5_mse: 5.3098 - loss: 12.9010
Epoch 80/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.1045 - dense_3_mse: 4.6364 - dense_5_mse: 5.7482 - loss: 14.4891
Epoch 81/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - dense_1_mse: 3.8298 - dense_3_mse: 4.3075 - dense_5_mse: 5.4416 - loss: 13.5789
Epoch 82/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.9316 - dense_3_mse: 4.1021 - dense_5_mse: 5.1823 - loss: 13.2159
Epoch 83/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.8672 - dense_3_mse: 4.2861 - dense_5_mse: 7.1628 - loss: 15.3160
Epoch 84/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.9169 - dense_3_mse: 4.4441 - dense_5_mse: 5.5980 - loss: 13.9590
Epoch 85/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0149 - dense_3_mse: 4.3905 - dense_5_mse: 5.3098 - loss: 13.7152
Epoch 86/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6772 - dense_3_mse: 4.1107 - dense_5_mse: 5.8546 - loss: 13.6424
Epoch 87/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6984 - dense_3_mse: 4.0809 - dense_5_mse: 5.7615 - loss: 13.5407
Epoch 88/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - dense_1_mse: 4.0417 - dense_3_mse: 4.6002 - dense_5_mse: 6.5661 - loss: 15.2080
Epoch 89/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.8926 - dense_3_mse: 4.1050 - dense_5_mse: 5.4776 - loss: 13.4752
Epoch 90/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6670 - dense_3_mse: 4.1635 - dense_5_mse: 5.2522 - loss: 13.0827
Epoch 91/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.9877 - dense_3_mse: 4.0341 - dense_5_mse: 6.3160 - loss: 14.3378
Epoch 92/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - dense_1_mse: 3.5771 - dense_3_mse: 4.0076 - dense_5_mse: 5.6600 - loss: 13.2448
Epoch 93/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 3.6649 - dense_3_mse: 4.1621 - dense_5_mse: 5.8290 - loss: 13.6559
Epoch 94/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.8013 - dense_3_mse: 3.9163 - dense_5_mse: 5.6138 - loss: 13.3314
Epoch 95/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.4805 - dense_3_mse: 4.2661 - dense_5_mse: 5.6021 - loss: 13.3488
Epoch 96/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - dense_1_mse: 3.6476 - dense_3_mse: 3.9006 - dense_5_mse: 6.1371 - loss: 13.6853
Epoch 97/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.8402 - dense_3_mse: 5.0524 - dense_5_mse: 6.1900 - loss: 15.0827
Epoch 98/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0965 - dense_3_mse: 4.0310 - dense_5_mse: 6.3048 - loss: 14.4324
Epoch 99/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6706 - dense_3_mse: 4.4573 - dense_5_mse: 5.8490 - loss: 13.9769
Epoch 100/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - dense_1_mse: 3.7698 - dense_3_mse: 4.2139 - dense_5_mse: 5.3839 - loss: 13.3675
Epoch 101/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.7714 - dense_3_mse: 3.9499 - dense_5_mse: 4.8286 - loss: 12.5499
Epoch 102/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.4350 - dense_3_mse: 3.9778 - dense_5_mse: 5.0678 - loss: 12.4806
Epoch 103/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - dense_1_mse: 4.0873 - dense_3_mse: 4.2070 - dense_5_mse: 5.7904 - loss: 14.0847
Epoch 104/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 4.0010 - dense_3_mse: 4.0352 - dense_5_mse: 5.3971 - loss: 13.4332
Epoch 105/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 725us/step - dense_1_mse: 3.6684 - dense_3_mse: 4.2046 - dense_5_mse: 5.7630 - loss: 13.6360
Epoch 106/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - dense_1_mse: 3.5693 - dense_3_mse: 3.8949 - dense_5_mse: 4.6656 - loss: 12.1298
Epoch 107/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step - dense_1_mse: 3.3330 - dense_3_mse: 3.3443 - dense_5_mse: 5.1733 - loss: 11.8507
Epoch 108/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - dense_1_mse: 3.5602 - dense_3_mse: 3.5801 - dense_5_mse: 4.9893 - loss: 12.1296
Epoch 109/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - dense_1_mse: 3.4597 - dense_3_mse: 4.0578 - dense_5_mse: 5.1096 - loss: 12.6271
Epoch 110/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - dense_1_mse: 3.3128 - dense_3_mse: 3.3430 - dense_5_mse: 4.5491 - loss: 11.2049
Epoch 111/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - dense_1_mse: 3.7049 - dense_3_mse: 4.2773 - dense_5_mse: 6.1467 - loss: 14.1289
Epoch 112/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step - dense_1_mse: 3.8597 - dense_3_mse: 3.9922 - dense_5_mse: 6.1537 - loss: 14.0056
Epoch 113/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 3.6659 - dense_3_mse: 3.7883 - dense_5_mse: 4.6493 - loss: 12.1035
Epoch 114/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.4424 - dense_3_mse: 3.9755 - dense_5_mse: 4.8990 - loss: 12.3169
Epoch 115/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.4195 - dense_3_mse: 3.7017 - dense_5_mse: 4.2862 - loss: 11.4074
Epoch 116/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.2287 - dense_3_mse: 3.3350 - dense_5_mse: 4.5348 - loss: 11.0985
Epoch 117/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.2016 - dense_3_mse: 3.6776 - dense_5_mse: 5.2958 - loss: 12.1749
Epoch 118/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.3395 - dense_3_mse: 3.4299 - dense_5_mse: 4.8110 - loss: 11.5804
Epoch 119/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6684 - dense_3_mse: 3.9316 - dense_5_mse: 5.7554 - loss: 13.3555
Epoch 120/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.3114 - dense_3_mse: 3.4445 - dense_5_mse: 4.6498 - loss: 11.4056
Epoch 121/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.2229 - dense_3_mse: 3.6071 - dense_5_mse: 4.9966 - loss: 11.8266
Epoch 122/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - dense_1_mse: 3.7794 - dense_3_mse: 3.8427 - dense_5_mse: 4.5499 - loss: 12.1720
Epoch 123/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - dense_1_mse: 3.1977 - dense_3_mse: 3.1791 - dense_5_mse: 5.2461 - loss: 11.6229
Epoch 124/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.2498 - dense_3_mse: 3.6485 - dense_5_mse: 4.5740 - loss: 11.4723
Epoch 125/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.4510 - dense_3_mse: 4.1303 - dense_5_mse: 5.1024 - loss: 12.6836
Epoch 126/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - dense_1_mse: 3.6971 - dense_3_mse: 3.6964 - dense_5_mse: 4.7591 - loss: 12.1526
Epoch 127/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.6597 - dense_3_mse: 3.2572 - dense_5_mse: 4.4988 - loss: 11.4158
Epoch 128/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - dense_1_mse: 3.3925 - dense_3_mse: 3.6966 - dense_5_mse: 4.7056 - loss: 11.7947
Epoch 129/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.3047 - dense_3_mse: 3.5800 - dense_5_mse: 4.5836 - loss: 11.4683
Epoch 130/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.2205 - dense_3_mse: 3.3827 - dense_5_mse: 4.4587 - loss: 11.0619
Epoch 131/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.7387 - dense_3_mse: 3.6364 - dense_5_mse: 4.5094 - loss: 11.8845
Epoch 132/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - dense_1_mse: 3.3707 - dense_3_mse: 3.3984 - dense_5_mse: 4.1840 - loss: 10.9532
Epoch 133/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - dense_1_mse: 3.1912 - dense_3_mse: 3.4876 - dense_5_mse: 4.4389 - loss: 11.1178
Epoch 134/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.2252 - dense_3_mse: 3.4972 - dense_5_mse: 4.0971 - loss: 10.8195
Epoch 135/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.4718 - dense_3_mse: 3.2642 - dense_5_mse: 4.5634 - loss: 11.2994
Epoch 136/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.3047 - dense_3_mse: 3.5980 - dense_5_mse: 5.2577 - loss: 12.1604
Epoch 137/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.4898 - dense_3_mse: 3.4283 - dense_5_mse: 4.9106 - loss: 11.8287
Epoch 138/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.0691 - dense_3_mse: 3.4181 - dense_5_mse: 4.0013 - loss: 10.4886
Epoch 139/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.9429 - dense_3_mse: 4.5314 - dense_5_mse: 5.2769 - loss: 13.7512
Epoch 140/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - dense_1_mse: 3.4795 - dense_3_mse: 3.8584 - dense_5_mse: 4.8683 - loss: 12.2062
Epoch 141/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - dense_1_mse: 3.2083 - dense_3_mse: 3.8040 - dense_5_mse: 4.8874 - loss: 11.8997
Epoch 142/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - dense_1_mse: 3.4645 - dense_3_mse: 3.6403 - dense_5_mse: 4.3153 - loss: 11.4201
Epoch 143/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - dense_1_mse: 3.4129 - dense_3_mse: 3.5137 - dense_5_mse: 4.4685 - loss: 11.3951
Epoch 144/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - dense_1_mse: 3.4632 - dense_3_mse: 3.2676 - dense_5_mse: 4.4220 - loss: 11.1529
Epoch 145/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - dense_1_mse: 3.4894 - dense_3_mse: 3.5215 - dense_5_mse: 4.1864 - loss: 11.1973
Epoch 146/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - dense_1_mse: 3.1063 - dense_3_mse: 3.5544 - dense_5_mse: 3.9011 - loss: 10.5619
Epoch 147/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - dense_1_mse: 3.3992 - dense_3_mse: 3.5249 - dense_5_mse: 4.1532 - loss: 11.0773
Epoch 148/500

In [8]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 56)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 32)        │      1,824 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1)         │         33 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 57)        │          0 │ input_layer[0][0… │
│ (Concatenate)       │                   │            │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 32)        │      1,856 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 1)         │         33 │ dense_2[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_1       │ (None, 58)        │          0 │ input_layer[0][0… │
│ (Concatenate)       │                   │            │ dense_1[0][0],    │
│                     │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 32)        │      1,888 │ concatenate_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 1)         │         33 │ dense_4[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,003 (66.42 KB)

 Trainable params: 5,667 (22.14 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 11,336 (44.29 KB)

In [9]:
model.evaluate(x_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - dense_1_mse: 10.0051 - dense_3_mse: 0.0000e+00 - dense_5_mse: 0.0000e+00 - loss: 10.0051

[10.636868476867676, 10.636868476867676, 0.0, 0.0]

In [10]:
pred = model.predict(x_train)
pred = np.clip(pred, 0, 20).astype(int) # обрезка
pd.DataFrame(pred.reshape(519, 3)) # преобразуем в двухмерный массив

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

      0   1   2
0    14  11  11
1    12   9   9
2     6   8   7
3    11  11  12
4    11   9   8
..   ..  ..  ..
514  13  13  14
515  11  13  14
516  10  13  11
517  13  10  11
518  14  10  13

[519 rows x 3 columns]

In [11]:
pd.DataFrame(data_y)

     G1  G2  G3
0     0  11  11
1     9  11  11
2    12  13  12
3    14  14  14
4    11  13  13
..   ..  ..  ..
644  10  11  10
645  15  15  16
646  11  12   9
647  10  10  10
648  10  11  11

[649 rows x 3 columns]