Deep Lerning. We will search G1, G2 and after G3.

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

In [30]:
student_performance = fetch_ucirepo(id=320) 

data_X = student_performance.data.features
data_y = student_performance.data.targets

X = pd.get_dummies(data_X)
y = data_y


# При использовании pd.get_dummies для преобразования категориальных признаков в dummy-переменные, нет необходимости в явном использовании слоя нормализации в модели. 
# Это потому, что pd.get_dummies создает бинарные (или dummy) переменные, которые по своей природе уже нормализованы (их значения находятся в диапазоне [0, 1]).
# слой Flatten так же не нужен

0       True
1       True
2      False
3       True
4       True
       ...
644     True
645    False
646     True
647    False
648    False
Name: famsize_GT3, Length: 649, dtype: bool

In [21]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

(519, 58)

In [11]:
x_train = x_train.astype(float)
x_test = x_test.astype(float)

In [12]:
normalizer = Normalization()
normalizer.adapt(x_train.values)

In [14]:
X["G2"]

0      11
1      11
2      13
3      14
4      13
       ..
644    11
645    15
646    12
647    10
648    11
Name: G2, Length: 649, dtype: int64

In [15]:
model.compile(optimizer="rmsprop", loss="mean_squared_error", metrics=["acc"])

In [16]:
model.fit(x_train, y_train, epochs=200, validation_data=(x_test, y_test))

Epoch 1/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.0122 - loss: 121.3936 - val_acc: 0.0077 - val_loss: 115.0760
Epoch 2/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0011 - loss: 99.5918 - val_acc: 0.0000e+00 - val_loss: 96.4832
Epoch 3/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0104 - loss: 85.3344 - val_acc: 0.0000e+00 - val_loss: 79.5294
Epoch 4/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0025 - loss: 71.7676 - val_acc: 0.0000e+00 - val_loss: 64.1949
Epoch 5/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0014 - loss: 52.3036 - val_acc: 0.0000e+00 - val_loss: 49.5983
Epoch 6/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0035 - loss: 41.3566 - val_acc: 0.0000e+00 - val_loss: 37.2359
Epoch 7/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 5.6234e-04 - loss: 29.3962 - val_acc: 0.0000e+00 - val_loss: 26.7357
Epoch 8/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 4.3833e-04 - loss: 21.3651 - val_acc: 0.0000e+00 - val_loss: 18.5418
Epoch 9/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 3.2259e-04 - loss: 13.5782 - val_acc: 0.0000e+00 - val_loss: 12.5721
Epoch 10/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0061 - loss: 9.8847 - val_acc: 0.0000e+00 - val_loss: 8.9157
Epoch 11/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 9.9839e-04 - loss: 5.8962 - val_acc: 0.0000e+00 - val_loss: 6.8666
Epoch 12/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0043 - loss: 5.5128 - val_acc: 0.0000e+00 - val_loss: 5.7439
Epoch 13/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 3.8792 - val_acc: 0.0000e+00 - val_loss: 5.0669
Epoch 14/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0012 - loss: 3.8008 - val_acc: 0.0000e+00 - val_loss: 4.9682
Epoch 15/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0014 - loss: 3.0566 - val_acc: 0.0000e+00 - val_loss: 4.7745
Epoch 16/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 8.4057e-04 - loss: 2.6704 - val_acc: 0.0000e+00 - val_loss: 4.5782
Epoch 17/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 6.9589e-04 - loss: 2.4964 - val_acc: 0.0000e+00 - val_loss: 4.4706
Epoch 18/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0012 - loss: 2.3949 - val_acc: 0.0000e+00 - val_loss: 4.3738
Epoch 19/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0029 - loss: 2.2545 - val_acc: 0.0000e+00 - val_loss: 4.3266
Epoch 20/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0016 - loss: 1.9157 - val_acc: 0.0000e+00 - val_loss: 4.2397
Epoch 21/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0025 - loss: 2.0276 - val_acc: 0.0000e+00 - val_loss: 4.2839
Epoch 22/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 3.2259e-04 - loss: 2.0188 - val_acc: 0.0000e+00 - val_loss: 4.0901
Epoch 23/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0035 - loss: 1.9106 - val_acc: 0.0000e+00 - val_loss: 3.9857
Epoch 24/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 4.3833e-04 - loss: 1.7489 - val_acc: 0.0000e+00 - val_loss: 3.9030
Epoch 25/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 1.5235 - val_acc: 0.0000e+00 - val_loss: 3.7566
Epoch 26/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 4.3833e-04 - loss: 1.4854 - val_acc: 0.0000e+00 - val_loss: 3.6876
Epoch 27/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 8.4057e-04 - loss: 1.2149 - val_acc: 0.0000e+00 - val_loss: 3.6990
Epoch 28/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0016 - loss: 1.2302 - val_acc: 0.0000e+00 - val_loss: 3.5968
Epoch 29/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 5.6234e-04 - loss: 1.1296 - val_acc: 0.0000e+00 - val_loss: 3.6127
Epoch 30/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 6.9589e-04 - loss: 1.0945 - val_acc: 0.0000e+00 - val_loss: 3.5229
Epoch 31/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0025 - loss: 0.9546 - val_acc: 0.0000e+00 - val_loss: 3.4215
Epoch 32/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0043 - loss: 1.1052 - val_acc: 0.0000e+00 - val_loss: 3.3612
Epoch 33/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 4.3833e-04 - loss: 0.9567 - val_acc: 0.0000e+00 - val_loss: 3.3386
Epoch 34/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 9.9839e-04 - loss: 0.8004 - val_acc: 0.0000e+00 - val_loss: 3.3344
Epoch 35/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0021 - loss: 0.9360 - val_acc: 0.0000e+00 - val_loss: 3.2057
Epoch 36/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0035 - loss: 0.7967 - val_acc: 0.0000e+00 - val_loss: 3.2490
Epoch 37/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0034 - loss: 0.7125 - val_acc: 0.0000e+00 - val_loss: 3.2598
Epoch 38/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0129 - loss: 0.8491 - val_acc: 0.0000e+00 - val_loss: 3.1309
Epoch 39/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0067 - loss: 0.7178 - val_acc: 0.0000e+00 - val_loss: 3.1188
Epoch 40/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0032 - loss: 0.5332 - val_acc: 0.0000e+00 - val_loss: 3.1794
Epoch 41/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0063 - loss: 0.5613 - val_acc: 0.0000e+00 - val_loss: 3.0888
Epoch 42/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0090 - loss: 0.4845 - val_acc: 0.0000e+00 - val_loss: 3.0857
Epoch 43/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0053 - loss: 0.5470 - val_acc: 0.0000e+00 - val_loss: 3.1261
Epoch 44/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0065 - loss: 0.5326 - val_acc: 0.0000e+00 - val_loss: 3.0514
Epoch 45/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0093 - loss: 0.4626 - val_acc: 0.0000e+00 - val_loss: 3.0824
Epoch 46/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0078 - loss: 0.5915 - val_acc: 0.0000e+00 - val_loss: 3.0654
Epoch 47/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0080 - loss: 0.4256 - val_acc: 0.0000e+00 - val_loss: 3.0734
Epoch 48/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0149 - loss: 0.4028 - val_acc: 0.0000e+00 - val_loss: 2.9439
Epoch 49/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0093 - loss: 0.3937 - val_acc: 0.0000e+00 - val_loss: 2.9792
Epoch 50/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0169 - loss: 0.3636 - val_acc: 0.0000e+00 - val_loss: 3.0487
Epoch 51/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0074 - loss: 0.3055 - val_acc: 0.0000e+00 - val_loss: 2.9851
Epoch 52/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0067 - loss: 0.2987 - val_acc: 0.0000e+00 - val_loss: 2.9901
Epoch 53/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0159 - loss: 0.3126 - val_acc: 0.0000e+00 - val_loss: 2.9820
Epoch 54/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0134 - loss: 0.2747 - val_acc: 0.0000e+00 - val_loss: 2.9232
Epoch 55/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0128 - loss: 0.2619 - val_acc: 0.0000e+00 - val_loss: 2.9387
Epoch 56/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0099 - loss: 0.2740 - val_acc: 0.0000e+00 - val_loss: 3.0300
Epoch 57/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0142 - loss: 0.2120 - val_acc: 0.0000e+00 - val_loss: 2.9108
Epoch 58/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0133 - loss: 0.2361 - val_acc: 0.0000e+00 - val_loss: 2.8835
Epoch 59/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0185 - loss: 0.2341 - val_acc: 0.0000e+00 - val_loss: 2.9240
Epoch 60/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0130 - loss: 0.1996 - val_acc: 0.0000e+00 - val_loss: 3.0176
Epoch 61/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0203 - loss: 0.2344 - val_acc: 0.0000e+00 - val_loss: 2.9590
Epoch 62/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0093 - loss: 0.1796 - val_acc: 0.0000e+00 - val_loss: 2.8858
Epoch 63/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0197 - loss: 0.1788 - val_acc: 0.0000e+00 - val_loss: 2.8877
Epoch 64/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0155 - loss: 0.1890 - val_acc: 0.0000e+00 - val_loss: 2.9382
Epoch 65/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0123 - loss: 0.1701 - val_acc: 0.0000e+00 - val_loss: 2.8811
Epoch 66/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0150 - loss: 0.1355 - val_acc: 0.0000e+00 - val_loss: 2.8636
Epoch 67/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0161 - loss: 0.1799 - val_acc: 0.0000e+00 - val_loss: 2.9504
Epoch 68/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0172 - loss: 0.1356 - val_acc: 0.0000e+00 - val_loss: 2.9066
Epoch 69/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0185 - loss: 0.1137 - val_acc: 0.0000e+00 - val_loss: 2.8267
Epoch 70/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0168 - loss: 0.1407 - val_acc: 0.0077 - val_loss: 2.9000
Epoch 71/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0156 - loss: 0.1017 - val_acc: 0.0000e+00 - val_loss: 2.8215
Epoch 72/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0129 - loss: 0.1027 - val_acc: 0.0000e+00 - val_loss: 2.8489
Epoch 73/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0169 - loss: 0.1098 - val_acc: 0.0000e+00 - val_loss: 2.8224
Epoch 74/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0182 - loss: 0.0816 - val_acc: 0.0077 - val_loss: 2.8654
Epoch 75/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0172 - loss: 0.0877 - val_acc: 0.0077 - val_loss: 2.8033
Epoch 76/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0136 - loss: 0.0815 - val_acc: 0.0077 - val_loss: 2.8765
Epoch 77/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0280 - loss: 0.0802 - val_acc: 0.0077 - val_loss: 2.9388
Epoch 78/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0169 - loss: 0.0695 - val_acc: 0.0077 - val_loss: 2.8927
Epoch 79/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0146 - loss: 0.0628 - val_acc: 0.0077 - val_loss: 2.8667
Epoch 80/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0267 - loss: 0.0675 - val_acc: 0.0077 - val_loss: 2.8690
Epoch 81/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0219 - loss: 0.0620 - val_acc: 0.0000e+00 - val_loss: 2.8881
Epoch 82/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0211 - loss: 0.0531 - val_acc: 0.0000e+00 - val_loss: 2.8616
Epoch 83/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0185 - loss: 0.0485 - val_acc: 0.0077 - val_loss: 2.9903
Epoch 84/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0138 - loss: 0.0506 - val_acc: 0.0077 - val_loss: 2.9561
Epoch 85/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0225 - loss: 0.0486 - val_acc: 0.0077 - val_loss: 2.8758
Epoch 86/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0237 - loss: 0.0429 - val_acc: 0.0077 - val_loss: 2.9298
Epoch 87/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0223 - loss: 0.0351 - val_acc: 0.0077 - val_loss: 2.9600
Epoch 88/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0211 - loss: 0.0315 - val_acc: 0.0077 - val_loss: 2.9375
Epoch 89/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0241 - loss: 0.0373 - val_acc: 0.0077 - val_loss: 2.9478
Epoch 90/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0369 - loss: 0.0285 - val_acc: 0.0077 - val_loss: 2.8780
Epoch 91/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0289 - loss: 0.0301 - val_acc: 0.0077 - val_loss: 2.8189
Epoch 92/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0221 - loss: 0.0258 - val_acc: 0.0077 - val_loss: 2.9254
Epoch 93/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0353 - loss: 0.0261 - val_acc: 0.0077 - val_loss: 2.9239
Epoch 94/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0288 - loss: 0.0239 - val_acc: 0.0077 - val_loss: 2.9368
Epoch 95/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0284 - loss: 0.0245 - val_acc: 0.0077 - val_loss: 2.8672
Epoch 96/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0248 - loss: 0.0236 - val_acc: 0.0077 - val_loss: 2.8443
Epoch 97/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0285 - loss: 0.0222 - val_acc: 0.0077 - val_loss: 2.9527
Epoch 98/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0258 - loss: 0.0293 - val_acc: 0.0077 - val_loss: 2.8623
Epoch 99/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0210 - loss: 0.0216 - val_acc: 0.0077 - val_loss: 2.9004
Epoch 100/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0300 - loss: 0.0195 - val_acc: 0.0077 - val_loss: 2.9060
Epoch 101/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0179 - loss: 0.0152 - val_acc: 0.0077 - val_loss: 2.9306
Epoch 102/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0307 - loss: 0.0171 - val_acc: 0.0077 - val_loss: 2.9394
Epoch 103/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0270 - loss: 0.0207 - val_acc: 0.0077 - val_loss: 2.9464
Epoch 104/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0276 - loss: 0.0174 - val_acc: 0.0077 - val_loss: 2.9776
Epoch 105/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0292 - loss: 0.0160 - val_acc: 0.0077 - val_loss: 2.9352
Epoch 106/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0289 - loss: 0.0235 - val_acc: 0.0077 - val_loss: 2.9152
Epoch 107/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.0408 - loss: 0.0158 - val_acc: 0.0077 - val_loss: 2.8957
Epoch 108/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0242 - loss: 0.0168 - val_acc: 0.0077 - val_loss: 2.8736
Epoch 109/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0303 - loss: 0.0132 - val_acc: 0.0077 - val_loss: 2.9834
Epoch 110/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0244 - loss: 0.0179 - val_acc: 0.0077 - val_loss: 2.8873
Epoch 111/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0343 - loss: 0.0123 - val_acc: 0.0077 - val_loss: 2.9204
Epoch 112/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0244 - loss: 0.0157 - val_acc: 0.0077 - val_loss: 2.9576
Epoch 113/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0285 - loss: 0.0161 - val_acc: 0.0077 - val_loss: 2.9048
Epoch 114/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0239 - loss: 0.0167 - val_acc: 0.0077 - val_loss: 3.0289
Epoch 115/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0324 - loss: 0.0261 - val_acc: 0.0077 - val_loss: 2.9378
Epoch 116/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0356 - loss: 0.0131 - val_acc: 0.0077 - val_loss: 2.9637
Epoch 117/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0291 - loss: 0.0132 - val_acc: 0.0077 - val_loss: 2.9533
Epoch 118/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0319 - loss: 0.0127 - val_acc: 0.0077 - val_loss: 2.9695
Epoch 119/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0193 - loss: 0.0217 - val_acc: 0.0077 - val_loss: 2.9303
Epoch 120/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0289 - loss: 0.0166 - val_acc: 0.0077 - val_loss: 2.9969
Epoch 121/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0172 - loss: 0.0169 - val_acc: 0.0077 - val_loss: 2.9129
Epoch 122/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.0311 - loss: 0.0123 - val_acc: 0.0077 - val_loss: 2.9719
Epoch 123/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0197 - loss: 0.0141 - val_acc: 0.0077 - val_loss: 2.9505
Epoch 124/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0394 - loss: 0.0125 - val_acc: 0.0077 - val_loss: 2.9158
Epoch 125/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0197 - loss: 0.0160 - val_acc: 0.0077 - val_loss: 2.9307
Epoch 126/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0328 - loss: 0.0165 - val_acc: 0.0077 - val_loss: 2.9619
Epoch 127/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0256 - loss: 0.0136 - val_acc: 0.0077 - val_loss: 3.0025
Epoch 128/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0368 - loss: 0.0168 - val_acc: 0.0077 - val_loss: 2.9547
Epoch 129/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0292 - loss: 0.0090 - val_acc: 0.0077 - val_loss: 2.8939
Epoch 130/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0268 - loss: 0.0164 - val_acc: 0.0077 - val_loss: 2.9635
Epoch 131/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0316 - loss: 0.0128 - val_acc: 0.0077 - val_loss: 3.0184
Epoch 132/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0236 - loss: 0.0146 - val_acc: 0.0077 - val_loss: 2.9582
Epoch 133/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0287 - loss: 0.0134 - val_acc: 0.0077 - val_loss: 2.9248
Epoch 134/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0236 - loss: 0.0141 - val_acc: 0.0077 - val_loss: 2.9455
Epoch 135/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0262 - loss: 0.0164 - val_acc: 0.0077 - val_loss: 2.9475
Epoch 136/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0281 - loss: 0.0165 - val_acc: 0.0077 - val_loss: 2.9044
Epoch 137/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0324 - loss: 0.0147 - val_acc: 0.0077 - val_loss: 3.0213
Epoch 138/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0232 - loss: 0.0141 - val_acc: 0.0077 - val_loss: 2.9128
Epoch 139/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0262 - loss: 0.0235 - val_acc: 0.0077 - val_loss: 2.8977
Epoch 140/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0266 - loss: 0.0099 - val_acc: 0.0077 - val_loss: 2.9271
Epoch 141/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0244 - loss: 0.0165 - val_acc: 0.0077 - val_loss: 2.8458
Epoch 142/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0232 - loss: 0.0230 - val_acc: 0.0077 - val_loss: 2.9285
Epoch 143/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0356 - loss: 0.0090 - val_acc: 0.0077 - val_loss: 2.8614
Epoch 144/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0327 - loss: 0.0205 - val_acc: 0.0077 - val_loss: 2.9810
Epoch 145/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0285 - loss: 0.0104 - val_acc: 0.0077 - val_loss: 2.9478
Epoch 146/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0335 - loss: 0.0108 - val_acc: 0.0077 - val_loss: 2.9287
Epoch 147/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0353 - loss: 0.0137 - val_acc: 0.0077 - val_loss: 2.9810
Epoch 148/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0238 - loss: 0.0168 - val_acc: 0.0077 - val_loss: 2.9434
Epoch 149/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0226 - loss: 0.0133 - val_acc: 0.0077 - val_loss: 2.9762
Epoch 150/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0374 - loss: 0.0123 - val_acc: 0.0077 - val_loss: 3.0286
Epoch 151/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0311 - loss: 0.0209 - val_acc: 0.0077 - val_loss: 2.9354
Epoch 152/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0338 - loss: 0.0173 - val_acc: 0.0077 - val_loss: 2.9040
Epoch 153/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0173 - loss: 0.0120 - val_acc: 0.0077 - val_loss: 2.9615
Epoch 154/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0278 - loss: 0.0113 - val_acc: 0.0077 - val_loss: 2.9253
Epoch 155/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0268 - loss: 0.0152 - val_acc: 0.0077 - val_loss: 2.8950
Epoch 156/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0275 - loss: 0.0131 - val_acc: 0.0077 - val_loss: 2.9811
Epoch 157/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0220 - loss: 0.0161 - val_acc: 0.0077 - val_loss: 2.9727
Epoch 158/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0290 - loss: 0.0121 - val_acc: 0.0077 - val_loss: 2.9811
Epoch 159/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0226 - loss: 0.0150 - val_acc: 0.0077 - val_loss: 2.9835
Epoch 160/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0182 - loss: 0.0161 - val_acc: 0.0077 - val_loss: 2.8991
Epoch 161/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0284 - loss: 0.0191 - val_acc: 0.0077 - val_loss: 2.9734
Epoch 162/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0281 - loss: 0.0125 - val_acc: 0.0077 - val_loss: 2.8992
Epoch 163/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0270 - loss: 0.0142 - val_acc: 0.0077 - val_loss: 3.0273
Epoch 164/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0277 - loss: 0.0162 - val_acc: 0.0077 - val_loss: 2.9312
Epoch 165/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0279 - loss: 0.0124 - val_acc: 0.0077 - val_loss: 2.8777
Epoch 166/200

In [17]:
pred = model.predict(x_train)
pred = np.clip(pred, 0, 20).astype(int) # обрезка
pd.DataFrame(pred)

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

      0
0    17
1    11
2    12
3    13
4     9
..   ..
514  10
515   9
516  15
517   9
518  12

[519 rows x 1 columns]

In [18]:
pd.DataFrame(data_y)

     G3
0    11
1    11
2    12
3    14
4    13
..   ..
644  10
645  16
646   9
647  10
648  11

[649 rows x 1 columns]