In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, Flatten, Normalization
from tensorflow.keras.utils import to_categorical
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

In [184]:
student_performance = fetch_ucirepo(id=320) 

data_X = student_performance.data.features
data_y = student_performance.data.targets

data_X["G1"] = data_y["G1"]
data_X["G2"] = data_y["G2"]

data_y = data_y["G3"]

X = pd.get_dummies(data_X)
y = data_y

C:\Users\ivanz\AppData\Local\Temp\ipykernel_9328\3188500191.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_X["G1"] = data_y["G1"]
C:\Users\ivanz\AppData\Local\Temp\ipykernel_9328\3188500191.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_X["G2"] = data_y["G2"]

In [185]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [186]:
x_train = x_train.astype(float)
x_test = x_test.astype(float)

In [187]:
normalizer = Normalization()
normalizer.adapt(x_train.values)

In [188]:
model = Sequential([
    Input(shape=(58,)),
    normalizer,
    Flatten(),
    Dense(64, activation="relu"),
    Dense(1, activation="relu")
])

In [189]:
X["G2"]

0      11
1      11
2      13
3      14
4      13
       ..
644    11
645    15
646    12
647    10
648    11
Name: G2, Length: 649, dtype: int64

In [190]:
model.compile(optimizer="rmsprop", loss="mean_squared_error", metrics=["acc"])

In [191]:
model.fit(x_train, y_train, epochs=200, validation_data=(x_test, y_test))

Epoch 1/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.0035 - loss: 124.9471 - val_acc: 0.0000e+00 - val_loss: 112.1655
Epoch 2/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0072 - loss: 101.5306 - val_acc: 0.0000e+00 - val_loss: 93.6941
Epoch 3/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0062 - loss: 82.5951 - val_acc: 0.0000e+00 - val_loss: 76.1674
Epoch 4/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 9.9839e-04 - loss: 68.1078 - val_acc: 0.0000e+00 - val_loss: 61.0683
Epoch 5/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0043 - loss: 54.8306 - val_acc: 0.0000e+00 - val_loss: 48.0310
Epoch 6/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0012 - loss: 41.6684 - val_acc: 0.0000e+00 - val_loss: 36.1379
Epoch 7/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 30.2551 - val_acc: 0.0000e+00 - val_loss: 26.8900
Epoch 8/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0014 - loss: 21.9693 - val_acc: 0.0000e+00 - val_loss: 19.2925
Epoch 9/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 9.9839e-04 - loss: 14.1845 - val_acc: 0.0000e+00 - val_loss: 13.9196
Epoch 10/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 3.2259e-04 - loss: 9.8008 - val_acc: 0.0000e+00 - val_loss: 9.8351
Epoch 11/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0035 - loss: 6.8091 - val_acc: 0.0000e+00 - val_loss: 7.1605
Epoch 12/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0012 - loss: 5.1071 - val_acc: 0.0000e+00 - val_loss: 5.6626
Epoch 13/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 6.9589e-04 - loss: 4.1972 - val_acc: 0.0000e+00 - val_loss: 4.7303
Epoch 14/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0043 - loss: 3.9841 - val_acc: 0.0000e+00 - val_loss: 4.2687
Epoch 15/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0012 - loss: 3.6604 - val_acc: 0.0000e+00 - val_loss: 3.8998
Epoch 16/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0014 - loss: 3.0843 - val_acc: 0.0000e+00 - val_loss: 3.7163
Epoch 17/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 4.3833e-04 - loss: 2.7161 - val_acc: 0.0000e+00 - val_loss: 3.7514
Epoch 18/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 8.4057e-04 - loss: 2.6489 - val_acc: 0.0000e+00 - val_loss: 3.5697
Epoch 19/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 3.2259e-04 - loss: 2.4767 - val_acc: 0.0000e+00 - val_loss: 3.5234
Epoch 20/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 6.9589e-04 - loss: 2.2509 - val_acc: 0.0000e+00 - val_loss: 3.4740
Epoch 21/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0014 - loss: 1.9800 - val_acc: 0.0000e+00 - val_loss: 3.2522
Epoch 22/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0043 - loss: 2.1524 - val_acc: 0.0000e+00 - val_loss: 3.3037
Epoch 23/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0014 - loss: 1.8864 - val_acc: 0.0000e+00 - val_loss: 3.2421
Epoch 24/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0018 - loss: 1.5864 - val_acc: 0.0000e+00 - val_loss: 3.1134
Epoch 25/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 9.9839e-04 - loss: 1.3946 - val_acc: 0.0000e+00 - val_loss: 3.1155
Epoch 26/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0021 - loss: 1.3981 - val_acc: 0.0000e+00 - val_loss: 2.9957
Epoch 27/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 8.4057e-04 - loss: 1.3461 - val_acc: 0.0000e+00 - val_loss: 2.9971
Epoch 28/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 8.4057e-04 - loss: 1.1944 - val_acc: 0.0000e+00 - val_loss: 3.0523
Epoch 29/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 4.3833e-04 - loss: 1.1348 - val_acc: 0.0000e+00 - val_loss: 2.9061
Epoch 30/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0016 - loss: 1.1041 - val_acc: 0.0000e+00 - val_loss: 2.9182
Epoch 31/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0021 - loss: 1.0117 - val_acc: 0.0000e+00 - val_loss: 2.8905
Epoch 32/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0014 - loss: 0.9390 - val_acc: 0.0000e+00 - val_loss: 2.8315
Epoch 33/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 9.9839e-04 - loss: 1.0191 - val_acc: 0.0000e+00 - val_loss: 2.8419
Epoch 34/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 0.8169 - val_acc: 0.0000e+00 - val_loss: 2.8711
Epoch 35/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0016 - loss: 0.7025 - val_acc: 0.0000e+00 - val_loss: 2.8783
Epoch 36/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0018 - loss: 0.7550 - val_acc: 0.0000e+00 - val_loss: 2.8048
Epoch 37/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0012 - loss: 0.7082 - val_acc: 0.0077 - val_loss: 2.8001
Epoch 38/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 4.3833e-04 - loss: 0.6144 - val_acc: 0.0077 - val_loss: 2.8613
Epoch 39/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0036 - loss: 0.5702 - val_acc: 0.0077 - val_loss: 2.7681
Epoch 40/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0013 - loss: 0.5806 - val_acc: 0.0077 - val_loss: 2.6937
Epoch 41/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0051 - loss: 0.4904 - val_acc: 0.0077 - val_loss: 2.8188
Epoch 42/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0101 - loss: 0.4993 - val_acc: 0.0077 - val_loss: 2.7145
Epoch 43/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0052 - loss: 0.4779 - val_acc: 0.0077 - val_loss: 2.7753
Epoch 44/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0088 - loss: 0.4579 - val_acc: 0.0077 - val_loss: 2.9169
Epoch 45/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0065 - loss: 0.4051 - val_acc: 0.0077 - val_loss: 2.8773
Epoch 46/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0080 - loss: 0.3691 - val_acc: 0.0077 - val_loss: 2.6900
Epoch 47/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0194 - loss: 0.3860 - val_acc: 0.0077 - val_loss: 2.7918
Epoch 48/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0071 - loss: 0.3832 - val_acc: 0.0077 - val_loss: 2.9080
Epoch 49/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0141 - loss: 0.3491 - val_acc: 0.0077 - val_loss: 2.9020
Epoch 50/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0211 - loss: 0.3199 - val_acc: 0.0077 - val_loss: 2.7449
Epoch 51/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0124 - loss: 0.3443 - val_acc: 0.0077 - val_loss: 2.9233
Epoch 52/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0153 - loss: 0.2557 - val_acc: 0.0077 - val_loss: 2.8873
Epoch 53/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0126 - loss: 0.2852 - val_acc: 0.0077 - val_loss: 2.8129
Epoch 54/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0062 - loss: 0.2004 - val_acc: 0.0077 - val_loss: 2.8220
Epoch 55/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0133 - loss: 0.2192 - val_acc: 0.0077 - val_loss: 2.9429
Epoch 56/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0121 - loss: 0.2225 - val_acc: 0.0077 - val_loss: 2.8203
Epoch 57/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0133 - loss: 0.2001 - val_acc: 0.0077 - val_loss: 2.9301
Epoch 58/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0190 - loss: 0.1732 - val_acc: 0.0077 - val_loss: 2.8422
Epoch 59/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0192 - loss: 0.2018 - val_acc: 0.0077 - val_loss: 2.9188
Epoch 60/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0156 - loss: 0.1826 - val_acc: 0.0077 - val_loss: 2.7511
Epoch 61/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0185 - loss: 0.1632 - val_acc: 0.0077 - val_loss: 2.8697
Epoch 62/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0168 - loss: 0.1474 - val_acc: 0.0077 - val_loss: 2.8775
Epoch 63/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0147 - loss: 0.1357 - val_acc: 0.0077 - val_loss: 2.9490
Epoch 64/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0143 - loss: 0.1407 - val_acc: 0.0077 - val_loss: 2.8906
Epoch 65/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0182 - loss: 0.1352 - val_acc: 0.0077 - val_loss: 3.0824
Epoch 66/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0224 - loss: 0.1320 - val_acc: 0.0077 - val_loss: 2.9318
Epoch 67/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0131 - loss: 0.0997 - val_acc: 0.0077 - val_loss: 3.0976
Epoch 68/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0252 - loss: 0.1171 - val_acc: 0.0077 - val_loss: 2.8773
Epoch 69/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0154 - loss: 0.1040 - val_acc: 0.0077 - val_loss: 3.0356
Epoch 70/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0200 - loss: 0.1070 - val_acc: 0.0077 - val_loss: 2.9736
Epoch 71/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0127 - loss: 0.0974 - val_acc: 0.0077 - val_loss: 2.9666
Epoch 72/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0237 - loss: 0.0812 - val_acc: 0.0077 - val_loss: 2.9898
Epoch 73/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0215 - loss: 0.0692 - val_acc: 0.0077 - val_loss: 3.0426
Epoch 74/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0199 - loss: 0.0775 - val_acc: 0.0077 - val_loss: 3.0406
Epoch 75/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0128 - loss: 0.0693 - val_acc: 0.0077 - val_loss: 3.1316
Epoch 76/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0271 - loss: 0.0652 - val_acc: 0.0077 - val_loss: 3.1433
Epoch 77/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0253 - loss: 0.0806 - val_acc: 0.0077 - val_loss: 3.0801
Epoch 78/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0186 - loss: 0.0666 - val_acc: 0.0077 - val_loss: 3.0586
Epoch 79/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0179 - loss: 0.0659 - val_acc: 0.0077 - val_loss: 3.0239
Epoch 80/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0248 - loss: 0.0510 - val_acc: 0.0077 - val_loss: 3.2479
Epoch 81/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0254 - loss: 0.0579 - val_acc: 0.0077 - val_loss: 3.2018
Epoch 82/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0184 - loss: 0.0440 - val_acc: 0.0077 - val_loss: 3.0497
Epoch 83/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0197 - loss: 0.0472 - val_acc: 0.0077 - val_loss: 3.1535
Epoch 84/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0277 - loss: 0.0461 - val_acc: 0.0077 - val_loss: 3.1860
Epoch 85/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0262 - loss: 0.0402 - val_acc: 0.0077 - val_loss: 3.1508
Epoch 86/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0231 - loss: 0.0448 - val_acc: 0.0077 - val_loss: 3.1753
Epoch 87/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0325 - loss: 0.0366 - val_acc: 0.0077 - val_loss: 3.1895
Epoch 88/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0188 - loss: 0.0320 - val_acc: 0.0077 - val_loss: 3.0754
Epoch 89/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0289 - loss: 0.0362 - val_acc: 0.0077 - val_loss: 3.0541
Epoch 90/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0209 - loss: 0.0389 - val_acc: 0.0077 - val_loss: 3.1032
Epoch 91/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0299 - loss: 0.0298 - val_acc: 0.0077 - val_loss: 3.1960
Epoch 92/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0192 - loss: 0.0374 - val_acc: 0.0077 - val_loss: 3.2601
Epoch 93/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0187 - loss: 0.0271 - val_acc: 0.0077 - val_loss: 3.1779
Epoch 94/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0317 - loss: 0.0338 - val_acc: 0.0077 - val_loss: 3.2382
Epoch 95/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0217 - loss: 0.0284 - val_acc: 0.0077 - val_loss: 3.1847
Epoch 96/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0267 - loss: 0.0272 - val_acc: 0.0077 - val_loss: 3.2566
Epoch 97/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0275 - loss: 0.0269 - val_acc: 0.0077 - val_loss: 3.2682
Epoch 98/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0272 - loss: 0.0259 - val_acc: 0.0077 - val_loss: 3.2288
Epoch 99/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0329 - loss: 0.0231 - val_acc: 0.0077 - val_loss: 3.1957
Epoch 100/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0173 - loss: 0.0308 - val_acc: 0.0077 - val_loss: 3.2057
Epoch 101/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0216 - loss: 0.0180 - val_acc: 0.0077 - val_loss: 3.4101
Epoch 102/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0275 - loss: 0.0242 - val_acc: 0.0077 - val_loss: 3.2783
Epoch 103/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0297 - loss: 0.0238 - val_acc: 0.0077 - val_loss: 3.1886
Epoch 104/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0443 - loss: 0.0183 - val_acc: 0.0077 - val_loss: 3.2549
Epoch 105/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0185 - loss: 0.0184 - val_acc: 0.0077 - val_loss: 3.2453
Epoch 106/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0266 - loss: 0.0213 - val_acc: 0.0077 - val_loss: 3.2827
Epoch 107/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0265 - loss: 0.0280 - val_acc: 0.0077 - val_loss: 3.1962
Epoch 108/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0205 - loss: 0.0170 - val_acc: 0.0077 - val_loss: 3.2615
Epoch 109/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0322 - loss: 0.0273 - val_acc: 0.0077 - val_loss: 3.2886
Epoch 110/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0292 - loss: 0.0170 - val_acc: 0.0077 - val_loss: 3.2891
Epoch 111/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0207 - loss: 0.0145 - val_acc: 0.0077 - val_loss: 3.2242
Epoch 112/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0395 - loss: 0.0151 - val_acc: 0.0077 - val_loss: 3.1927
Epoch 113/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0282 - loss: 0.0167 - val_acc: 0.0077 - val_loss: 3.2677
Epoch 114/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0243 - loss: 0.0161 - val_acc: 0.0077 - val_loss: 3.1663
Epoch 115/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0316 - loss: 0.0179 - val_acc: 0.0077 - val_loss: 3.1631
Epoch 116/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0247 - loss: 0.0197 - val_acc: 0.0077 - val_loss: 3.3413
Epoch 117/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0266 - loss: 0.0113 - val_acc: 0.0077 - val_loss: 3.3396
Epoch 118/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0300 - loss: 0.0221 - val_acc: 0.0077 - val_loss: 3.3952
Epoch 119/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0254 - loss: 0.0181 - val_acc: 0.0077 - val_loss: 3.1501
Epoch 120/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0331 - loss: 0.0156 - val_acc: 0.0077 - val_loss: 3.3104
Epoch 121/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0225 - loss: 0.0252 - val_acc: 0.0077 - val_loss: 3.2088
Epoch 122/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0217 - loss: 0.0110 - val_acc: 0.0077 - val_loss: 3.3165
Epoch 123/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0328 - loss: 0.0157 - val_acc: 0.0077 - val_loss: 3.1255
Epoch 124/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0216 - loss: 0.0185 - val_acc: 0.0077 - val_loss: 3.3434
Epoch 125/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0188 - loss: 0.0180 - val_acc: 0.0077 - val_loss: 3.2567
Epoch 126/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0287 - loss: 0.0140 - val_acc: 0.0077 - val_loss: 3.3006
Epoch 127/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0369 - loss: 0.0172 - val_acc: 0.0077 - val_loss: 3.3056
Epoch 128/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0244 - loss: 0.0155 - val_acc: 0.0077 - val_loss: 3.2432
Epoch 129/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0218 - loss: 0.0211 - val_acc: 0.0077 - val_loss: 3.2583
Epoch 130/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0282 - loss: 0.0153 - val_acc: 0.0077 - val_loss: 3.3385
Epoch 131/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0236 - loss: 0.0124 - val_acc: 0.0077 - val_loss: 3.3012
Epoch 132/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0197 - loss: 0.0116 - val_acc: 0.0077 - val_loss: 3.2096
Epoch 133/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0253 - loss: 0.0130 - val_acc: 0.0077 - val_loss: 3.3137
Epoch 134/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0253 - loss: 0.0250 - val_acc: 0.0077 - val_loss: 3.3609
Epoch 135/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0254 - loss: 0.0211 - val_acc: 0.0077 - val_loss: 3.3262
Epoch 136/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0320 - loss: 0.0155 - val_acc: 0.0077 - val_loss: 3.2613
Epoch 137/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0145 - loss: 0.0109 - val_acc: 0.0077 - val_loss: 3.2362
Epoch 138/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0275 - loss: 0.0190 - val_acc: 0.0077 - val_loss: 3.3128
Epoch 139/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0329 - loss: 0.0127 - val_acc: 0.0077 - val_loss: 3.3170
Epoch 140/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0159 - loss: 0.0148 - val_acc: 0.0077 - val_loss: 3.2326
Epoch 141/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0206 - loss: 0.0151 - val_acc: 0.0077 - val_loss: 3.3466
Epoch 142/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0235 - loss: 0.0183 - val_acc: 0.0077 - val_loss: 3.2668
Epoch 143/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0233 - loss: 0.0158 - val_acc: 0.0077 - val_loss: 3.3215
Epoch 144/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0295 - loss: 0.0158 - val_acc: 0.0077 - val_loss: 3.2795
Epoch 145/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0291 - loss: 0.0255 - val_acc: 0.0077 - val_loss: 3.2981
Epoch 146/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0262 - loss: 0.0185 - val_acc: 0.0077 - val_loss: 3.2524
Epoch 147/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0191 - loss: 0.0187 - val_acc: 0.0077 - val_loss: 3.3600
Epoch 148/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.0307 - loss: 0.0201 - val_acc: 0.0077 - val_loss: 3.3027
Epoch 149/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0173 - loss: 0.0094 - val_acc: 0.0077 - val_loss: 3.2897
Epoch 150/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0204 - loss: 0.0143 - val_acc: 0.0077 - val_loss: 3.3257
Epoch 151/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0213 - loss: 0.0146 - val_acc: 0.0077 - val_loss: 3.4232
Epoch 152/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0297 - loss: 0.0220 - val_acc: 0.0077 - val_loss: 3.2732
Epoch 153/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0234 - loss: 0.0092 - val_acc: 0.0077 - val_loss: 3.3074
Epoch 154/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0293 - loss: 0.0119 - val_acc: 0.0077 - val_loss: 3.3472
Epoch 155/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0281 - loss: 0.0226 - val_acc: 0.0077 - val_loss: 3.2235
Epoch 156/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0235 - loss: 0.0243 - val_acc: 0.0077 - val_loss: 3.3033
Epoch 157/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0253 - loss: 0.0144 - val_acc: 0.0077 - val_loss: 3.2625
Epoch 158/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0347 - loss: 0.0141 - val_acc: 0.0077 - val_loss: 3.3050
Epoch 159/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0287 - loss: 0.0128 - val_acc: 0.0077 - val_loss: 3.3128
Epoch 160/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0144 - loss: 0.0143 - val_acc: 0.0077 - val_loss: 3.4094
Epoch 161/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0301 - loss: 0.0153 - val_acc: 0.0077 - val_loss: 3.3354
Epoch 162/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0272 - loss: 0.0173 - val_acc: 0.0077 - val_loss: 3.3666
Epoch 163/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0217 - loss: 0.0121 - val_acc: 0.0077 - val_loss: 3.2139
Epoch 164/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0293 - loss: 0.0167 - val_acc: 0.0077 - val_loss: 3.2843
Epoch 165/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0188 - loss: 0.0198 - val_acc: 0.0077 - val_loss: 3.3457
Epoch 166/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0197 - loss: 0.0173 - val_acc: 0.0077 - val_loss: 3.2932
Epoch 167/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0180 - loss: 0.0228 - val_acc: 0.0077 - val_loss: 3.3290
Epoch 168/200

In [192]:
pred = model.predict(x_train)
pred = np.clip(pred, 0, 20).astype(int) # обрезка
pd.DataFrame(pred)

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

      0
0    18
1    11
2    12
3    12
4     9
..   ..
514   9
515  10
516  15
517   9
518  12

[519 rows x 1 columns]

In [193]:
pd.DataFrame(data_y)

     G3
0    11
1    11
2    12
3    14
4    13
..   ..
644  10
645  16
646   9
647  10
648  11

[649 rows x 1 columns]