In [194]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, Flatten, Normalization
from tensorflow.keras.utils import to_categorical
from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split

In [195]:
student_performance = fetch_ucirepo(id=320) 

data_X = student_performance.data.features
data_y = student_performance.data.targets

data_X = pd.DataFrame(data_X)
data_y = pd.DataFrame(data_y)

data_X.loc[:, "G1"] = data_y["G1"]
data_X.loc[:, "G2"] = data_y["G2"]

data_y = data_y["G3"]

X = pd.get_dummies(data_X)
y = data_y

In [196]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [197]:
x_train = x_train.astype(float)
x_test = x_test.astype(float)

In [198]:
normalizer = Normalization()
normalizer.adapt(x_train.values)

In [199]:
model = Sequential([
    Input(shape=(58,)),
    normalizer,
    Flatten(),
    Dense(64, activation="relu"),
    Dense(1, activation="relu")
])

In [200]:
X["G2"]

0      11
1      11
2      13
3      14
4      13
       ..
644    11
645    15
646    12
647    10
648    11
Name: G2, Length: 649, dtype: int64

In [201]:
model.compile(optimizer="rmsprop", loss="mean_squared_error", metrics=["acc"])

In [202]:
model.fit(x_train, y_train, epochs=200, validation_data=(x_test, y_test))

Epoch 1/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.0039 - loss: 142.4444 - val_acc: 0.0077 - val_loss: 145.4467
Epoch 2/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0075 - loss: 123.2594 - val_acc: 0.0077 - val_loss: 130.2676
Epoch 3/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0023 - loss: 109.3579 - val_acc: 0.0077 - val_loss: 114.7316
Epoch 4/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0037 - loss: 97.0690 - val_acc: 0.0077 - val_loss: 98.2383
Epoch 5/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0043 - loss: 77.7741 - val_acc: 0.0077 - val_loss: 81.1916
Epoch 6/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 64.0634 - val_acc: 0.0077 - val_loss: 64.5859
Epoch 7/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0016 - loss: 53.7431 - val_acc: 0.0077 - val_loss: 50.6466
Epoch 8/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 6.9589e-04 - loss: 36.9949 - val_acc: 0.0000e+00 - val_loss: 37.9099
Epoch 9/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0025 - loss: 27.9178 - val_acc: 0.0000e+00 - val_loss: 27.6221
Epoch 10/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0016 - loss: 19.1832 - val_acc: 0.0000e+00 - val_loss: 19.5055
Epoch 11/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 9.9839e-04 - loss: 13.1782 - val_acc: 0.0000e+00 - val_loss: 13.6312
Epoch 12/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 9.9839e-04 - loss: 9.9938 - val_acc: 0.0000e+00 - val_loss: 9.5203
Epoch 13/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 4.3833e-04 - loss: 6.7009 - val_acc: 0.0000e+00 - val_loss: 7.3640
Epoch 14/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 5.6234e-04 - loss: 5.6161 - val_acc: 0.0000e+00 - val_loss: 6.1344
Epoch 15/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 4.2846 - val_acc: 0.0000e+00 - val_loss: 5.4241
Epoch 16/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0021 - loss: 4.2773 - val_acc: 0.0000e+00 - val_loss: 4.9412
Epoch 17/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0012 - loss: 3.7960 - val_acc: 0.0000e+00 - val_loss: 4.7601
Epoch 18/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 8.4057e-04 - loss: 2.9838 - val_acc: 0.0000e+00 - val_loss: 4.4559
Epoch 19/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 9.9839e-04 - loss: 2.6323 - val_acc: 0.0000e+00 - val_loss: 4.3407
Epoch 20/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 4.3833e-04 - loss: 2.5662 - val_acc: 0.0000e+00 - val_loss: 4.2196
Epoch 21/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0021 - loss: 2.3332 - val_acc: 0.0000e+00 - val_loss: 4.2996
Epoch 22/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 8.4057e-04 - loss: 2.0614 - val_acc: 0.0000e+00 - val_loss: 4.2807
Epoch 23/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 6.9589e-04 - loss: 2.0230 - val_acc: 0.0000e+00 - val_loss: 4.1791
Epoch 24/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0016 - loss: 1.9252 - val_acc: 0.0000e+00 - val_loss: 4.0604
Epoch 25/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0029 - loss: 1.9074 - val_acc: 0.0000e+00 - val_loss: 4.1820
Epoch 26/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 3.2259e-04 - loss: 1.5340 - val_acc: 0.0000e+00 - val_loss: 4.0682
Epoch 27/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0035 - loss: 1.5775 - val_acc: 0.0000e+00 - val_loss: 3.9423
Epoch 28/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 4.3833e-04 - loss: 1.3341 - val_acc: 0.0000e+00 - val_loss: 4.0957
Epoch 29/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 1.2593 - val_acc: 0.0000e+00 - val_loss: 3.9336
Epoch 30/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0018 - loss: 1.2751 - val_acc: 0.0000e+00 - val_loss: 3.9278
Epoch 31/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 5.6234e-04 - loss: 1.1437 - val_acc: 0.0000e+00 - val_loss: 3.8898
Epoch 32/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0033 - loss: 1.0488 - val_acc: 0.0000e+00 - val_loss: 3.8273
Epoch 33/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0053 - loss: 1.2161 - val_acc: 0.0000e+00 - val_loss: 3.7462
Epoch 34/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0041 - loss: 0.9964 - val_acc: 0.0000e+00 - val_loss: 3.7522
Epoch 35/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0031 - loss: 0.9179 - val_acc: 0.0000e+00 - val_loss: 3.6926
Epoch 36/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0072 - loss: 0.8836 - val_acc: 0.0000e+00 - val_loss: 3.6879
Epoch 37/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0117 - loss: 0.8487 - val_acc: 0.0000e+00 - val_loss: 3.7685
Epoch 38/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0053 - loss: 0.7674 - val_acc: 0.0000e+00 - val_loss: 3.6887
Epoch 39/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0109 - loss: 0.7432 - val_acc: 0.0000e+00 - val_loss: 3.5674
Epoch 40/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0092 - loss: 0.8077 - val_acc: 0.0000e+00 - val_loss: 3.6429
Epoch 41/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0079 - loss: 0.7700 - val_acc: 0.0000e+00 - val_loss: 3.5274
Epoch 42/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0134 - loss: 0.6845 - val_acc: 0.0000e+00 - val_loss: 3.5884
Epoch 43/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0153 - loss: 0.6268 - val_acc: 0.0000e+00 - val_loss: 3.5558
Epoch 44/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0140 - loss: 0.5553 - val_acc: 0.0077 - val_loss: 3.4900
Epoch 45/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0097 - loss: 0.5466 - val_acc: 0.0077 - val_loss: 3.5072
Epoch 46/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0148 - loss: 0.4808 - val_acc: 0.0077 - val_loss: 3.5657
Epoch 47/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0170 - loss: 0.4642 - val_acc: 0.0077 - val_loss: 3.4732
Epoch 48/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0094 - loss: 0.4523 - val_acc: 0.0077 - val_loss: 3.4078
Epoch 49/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0146 - loss: 0.4513 - val_acc: 0.0077 - val_loss: 3.4347
Epoch 50/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0141 - loss: 0.3715 - val_acc: 0.0077 - val_loss: 3.4059
Epoch 51/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0075 - loss: 0.3647 - val_acc: 0.0077 - val_loss: 3.2935
Epoch 52/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0084 - loss: 0.3571 - val_acc: 0.0077 - val_loss: 3.3511
Epoch 53/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0093 - loss: 0.3508 - val_acc: 0.0077 - val_loss: 3.3211
Epoch 54/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0148 - loss: 0.3228 - val_acc: 0.0077 - val_loss: 3.3735
Epoch 55/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0234 - loss: 0.3185 - val_acc: 0.0077 - val_loss: 3.3803
Epoch 56/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0201 - loss: 0.2864 - val_acc: 0.0077 - val_loss: 3.3124
Epoch 57/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0178 - loss: 0.2738 - val_acc: 0.0077 - val_loss: 3.3611
Epoch 58/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0121 - loss: 0.2716 - val_acc: 0.0077 - val_loss: 3.3161
Epoch 59/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0107 - loss: 0.2414 - val_acc: 0.0077 - val_loss: 3.3112
Epoch 60/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0112 - loss: 0.2001 - val_acc: 0.0077 - val_loss: 3.2639
Epoch 61/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0115 - loss: 0.2074 - val_acc: 0.0077 - val_loss: 3.2645
Epoch 62/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0229 - loss: 0.2332 - val_acc: 0.0077 - val_loss: 3.2272
Epoch 63/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0175 - loss: 0.1840 - val_acc: 0.0077 - val_loss: 3.2022
Epoch 64/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0094 - loss: 0.1603 - val_acc: 0.0077 - val_loss: 3.3032
Epoch 65/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0141 - loss: 0.1962 - val_acc: 0.0077 - val_loss: 3.2908
Epoch 66/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0149 - loss: 0.1580 - val_acc: 0.0077 - val_loss: 3.3054
Epoch 67/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0142 - loss: 0.1551 - val_acc: 0.0077 - val_loss: 3.2848
Epoch 68/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0189 - loss: 0.1352 - val_acc: 0.0077 - val_loss: 3.3931
Epoch 69/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0153 - loss: 0.1577 - val_acc: 0.0077 - val_loss: 3.2048
Epoch 70/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0156 - loss: 0.1232 - val_acc: 0.0077 - val_loss: 3.2330
Epoch 71/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0165 - loss: 0.1161 - val_acc: 0.0077 - val_loss: 3.2288
Epoch 72/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0196 - loss: 0.1267 - val_acc: 0.0077 - val_loss: 3.1541
Epoch 73/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0147 - loss: 0.1091 - val_acc: 0.0077 - val_loss: 3.2477
Epoch 74/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0132 - loss: 0.1036 - val_acc: 0.0077 - val_loss: 3.3250
Epoch 75/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0212 - loss: 0.1110 - val_acc: 0.0077 - val_loss: 3.1710
Epoch 76/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0120 - loss: 0.0798 - val_acc: 0.0077 - val_loss: 3.2809
Epoch 77/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0230 - loss: 0.0882 - val_acc: 0.0077 - val_loss: 3.2408
Epoch 78/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0301 - loss: 0.0717 - val_acc: 0.0077 - val_loss: 3.3147
Epoch 79/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0141 - loss: 0.0682 - val_acc: 0.0077 - val_loss: 3.2064
Epoch 80/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0233 - loss: 0.0752 - val_acc: 0.0077 - val_loss: 3.2509
Epoch 81/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0204 - loss: 0.0653 - val_acc: 0.0077 - val_loss: 3.2014
Epoch 82/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0170 - loss: 0.0584 - val_acc: 0.0077 - val_loss: 3.4182
Epoch 83/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0268 - loss: 0.0699 - val_acc: 0.0077 - val_loss: 3.2567
Epoch 84/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0308 - loss: 0.0490 - val_acc: 0.0077 - val_loss: 3.1124
Epoch 85/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0222 - loss: 0.0539 - val_acc: 0.0077 - val_loss: 3.2189
Epoch 86/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0210 - loss: 0.0464 - val_acc: 0.0077 - val_loss: 3.2097
Epoch 87/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0227 - loss: 0.0386 - val_acc: 0.0077 - val_loss: 3.1347
Epoch 88/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0223 - loss: 0.0425 - val_acc: 0.0077 - val_loss: 3.3113
Epoch 89/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0259 - loss: 0.0456 - val_acc: 0.0077 - val_loss: 3.2866
Epoch 90/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0334 - loss: 0.0387 - val_acc: 0.0077 - val_loss: 3.2330
Epoch 91/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0266 - loss: 0.0367 - val_acc: 0.0077 - val_loss: 3.1165
Epoch 92/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0224 - loss: 0.0317 - val_acc: 0.0077 - val_loss: 3.1433
Epoch 93/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0274 - loss: 0.0324 - val_acc: 0.0077 - val_loss: 3.2857
Epoch 94/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0248 - loss: 0.0295 - val_acc: 0.0077 - val_loss: 3.1350
Epoch 95/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0303 - loss: 0.0362 - val_acc: 0.0077 - val_loss: 3.3006
Epoch 96/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0168 - loss: 0.0280 - val_acc: 0.0077 - val_loss: 3.2169
Epoch 97/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0280 - loss: 0.0316 - val_acc: 0.0077 - val_loss: 3.2046
Epoch 98/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0221 - loss: 0.0257 - val_acc: 0.0077 - val_loss: 3.1447
Epoch 99/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0299 - loss: 0.0262 - val_acc: 0.0077 - val_loss: 3.1505
Epoch 100/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0307 - loss: 0.0221 - val_acc: 0.0077 - val_loss: 3.1547
Epoch 101/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0221 - loss: 0.0247 - val_acc: 0.0077 - val_loss: 3.1502
Epoch 102/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0259 - loss: 0.0227 - val_acc: 0.0077 - val_loss: 3.1957
Epoch 103/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0299 - loss: 0.0246 - val_acc: 0.0077 - val_loss: 3.1621
Epoch 104/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0343 - loss: 0.0186 - val_acc: 0.0077 - val_loss: 3.1583
Epoch 105/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0238 - loss: 0.0162 - val_acc: 0.0077 - val_loss: 3.2114
Epoch 106/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0295 - loss: 0.0286 - val_acc: 0.0077 - val_loss: 3.2793
Epoch 107/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0301 - loss: 0.0232 - val_acc: 0.0077 - val_loss: 3.2684
Epoch 108/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0233 - loss: 0.0188 - val_acc: 0.0077 - val_loss: 3.1605
Epoch 109/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0287 - loss: 0.0194 - val_acc: 0.0077 - val_loss: 3.1998
Epoch 110/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0240 - loss: 0.0179 - val_acc: 0.0077 - val_loss: 3.2667
Epoch 111/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0369 - loss: 0.0180 - val_acc: 0.0077 - val_loss: 3.2658
Epoch 112/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0299 - loss: 0.0196 - val_acc: 0.0077 - val_loss: 3.2101
Epoch 113/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0249 - loss: 0.0154 - val_acc: 0.0077 - val_loss: 3.2523
Epoch 114/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0222 - loss: 0.0144 - val_acc: 0.0077 - val_loss: 3.2480
Epoch 115/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0307 - loss: 0.0141 - val_acc: 0.0077 - val_loss: 3.1787
Epoch 116/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0205 - loss: 0.0196 - val_acc: 0.0077 - val_loss: 3.2729
Epoch 117/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0318 - loss: 0.0177 - val_acc: 0.0077 - val_loss: 3.2526
Epoch 118/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0229 - loss: 0.0174 - val_acc: 0.0077 - val_loss: 3.1763
Epoch 119/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0220 - loss: 0.0160 - val_acc: 0.0077 - val_loss: 3.1723
Epoch 120/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0301 - loss: 0.0152 - val_acc: 0.0077 - val_loss: 3.2212
Epoch 121/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0345 - loss: 0.0204 - val_acc: 0.0077 - val_loss: 3.1217
Epoch 122/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0358 - loss: 0.0162 - val_acc: 0.0077 - val_loss: 3.2209
Epoch 123/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0259 - loss: 0.0164 - val_acc: 0.0077 - val_loss: 3.3039
Epoch 124/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0247 - loss: 0.0124 - val_acc: 0.0077 - val_loss: 3.2533
Epoch 125/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0259 - loss: 0.0116 - val_acc: 0.0077 - val_loss: 3.1954
Epoch 126/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0259 - loss: 0.0155 - val_acc: 0.0077 - val_loss: 3.2159
Epoch 127/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0254 - loss: 0.0165 - val_acc: 0.0077 - val_loss: 3.1020
Epoch 128/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0261 - loss: 0.0134 - val_acc: 0.0077 - val_loss: 3.1717
Epoch 129/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0278 - loss: 0.0146 - val_acc: 0.0077 - val_loss: 3.2441
Epoch 130/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0261 - loss: 0.0172 - val_acc: 0.0077 - val_loss: 3.1808
Epoch 131/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0209 - loss: 0.0195 - val_acc: 0.0077 - val_loss: 3.1600
Epoch 132/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0227 - loss: 0.0193 - val_acc: 0.0077 - val_loss: 3.2682
Epoch 133/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0309 - loss: 0.0119 - val_acc: 0.0077 - val_loss: 3.2275
Epoch 134/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0261 - loss: 0.0166 - val_acc: 0.0077 - val_loss: 3.2036
Epoch 135/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0277 - loss: 0.0110 - val_acc: 0.0077 - val_loss: 3.2773
Epoch 136/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0268 - loss: 0.0153 - val_acc: 0.0077 - val_loss: 3.2117
Epoch 137/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0305 - loss: 0.0117 - val_acc: 0.0077 - val_loss: 3.2277
Epoch 138/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0189 - loss: 0.0184 - val_acc: 0.0077 - val_loss: 3.2485
Epoch 139/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0275 - loss: 0.0126 - val_acc: 0.0077 - val_loss: 3.2289
Epoch 140/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0304 - loss: 0.0121 - val_acc: 0.0077 - val_loss: 3.2154
Epoch 141/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0193 - loss: 0.0187 - val_acc: 0.0077 - val_loss: 3.1720
Epoch 142/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0246 - loss: 0.0123 - val_acc: 0.0077 - val_loss: 3.2028
Epoch 143/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0254 - loss: 0.0119 - val_acc: 0.0077 - val_loss: 3.1285
Epoch 144/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0389 - loss: 0.0160 - val_acc: 0.0077 - val_loss: 3.2758
Epoch 145/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0314 - loss: 0.0185 - val_acc: 0.0077 - val_loss: 3.1967
Epoch 146/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0258 - loss: 0.0142 - val_acc: 0.0077 - val_loss: 3.2284
Epoch 147/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0230 - loss: 0.0187 - val_acc: 0.0077 - val_loss: 3.2168
Epoch 148/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0215 - loss: 0.0149 - val_acc: 0.0077 - val_loss: 3.2514
Epoch 149/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0204 - loss: 0.0152 - val_acc: 0.0077 - val_loss: 3.3105
Epoch 150/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0159 - loss: 0.0161 - val_acc: 0.0077 - val_loss: 3.2168
Epoch 151/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0301 - loss: 0.0125 - val_acc: 0.0077 - val_loss: 3.2033
Epoch 152/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0288 - loss: 0.0169 - val_acc: 0.0077 - val_loss: 3.2554
Epoch 153/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0293 - loss: 0.0120 - val_acc: 0.0077 - val_loss: 3.2180
Epoch 154/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0299 - loss: 0.0216 - val_acc: 0.0077 - val_loss: 3.2809
Epoch 155/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0286 - loss: 0.0140 - val_acc: 0.0077 - val_loss: 3.2799
Epoch 156/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0267 - loss: 0.0101 - val_acc: 0.0077 - val_loss: 3.1945
Epoch 157/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0231 - loss: 0.0134 - val_acc: 0.0077 - val_loss: 3.1929
Epoch 158/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0226 - loss: 0.0140 - val_acc: 0.0077 - val_loss: 3.2151
Epoch 159/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0303 - loss: 0.0171 - val_acc: 0.0077 - val_loss: 3.1851
Epoch 160/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0248 - loss: 0.0177 - val_acc: 0.0077 - val_loss: 3.2564
Epoch 161/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0242 - loss: 0.0137 - val_acc: 0.0077 - val_loss: 3.2694
Epoch 162/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0299 - loss: 0.0155 - val_acc: 0.0077 - val_loss: 3.2705
Epoch 163/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0225 - loss: 0.0136 - val_acc: 0.0077 - val_loss: 3.2045
Epoch 164/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0260 - loss: 0.0180 - val_acc: 0.0077 - val_loss: 3.1506
Epoch 165/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.0254 - loss: 0.0193 - val_acc: 0.0077 - val_loss: 3.2417
Epoch 166/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0261 - loss: 0.0118 - val_acc: 0.0077 - val_loss: 3.2872
Epoch 167/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.0384 - loss: 0.0110 - val_acc: 0.0077 - val_loss: 3.2246

In [203]:
pred = model.predict(x_train)
pred = np.clip(pred, 0, 20).astype(int) # обрезка
pd.DataFrame(pred)

17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

      0
0    17
1    11
2    12
3    12
4    10
..   ..
514  10
515  10
516  15
517   9
518  11

[519 rows x 1 columns]

In [204]:
pd.DataFrame(data_y)

     G3
0    11
1    11
2    12
3    14
4    13
..   ..
644  10
645  16
646   9
647  10
648  11

[649 rows x 1 columns]