In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding, Dropout, LSTM, Normalization, Input

In [83]:
BATCH_SIZE = 64
EPOCHS = 30
TRAIN_DIRECTORY = "big-files/transactions100000.csv"

In [84]:
# from pandas_gbq import read_gbq

# from google.cloud import bigquery
# from google.oauth2 import service_account


# KEY = "/big-files/idyllic-tendril-421208-5bc1941f7008.json"

# credentials = service_account.Credentials.from_service_account_file(KEY)

# client = bigquery.Client(credentials=credentials, project=credentials.project_id)

# table_id = 'bigquery-public-data.crypto_ethereum.transactions'

# query = f"""
# SELECT *
# FROM "{table_id}"
# LIMIT 1000
# WHERE block_timestamp >= '2024-01-01'
# """

# data = read_gbq(query, project_id=credentials.project_id, credentials=credentials)

In [85]:
data = pd.read_csv(TRAIN_DIRECTORY)
data

,hash,nonce,transaction_index,from_address,to_address,value,gas,gas_price,input,receipt_cumulative_gas_used,...,block_number,block_hash,max_fee_per_gas,max_priority_fee_per_gas,transaction_type,receipt_effective_gas_price,max_fee_per_blob_gas,blob_versioned_hashes,receipt_blob_gas_price,receipt_blob_gas_used
0,0xe762dd92f7a7bc16ee47188c4a2dfedc28202dad13c4...,57077,148,0xa83114a443da1cecefc50368531cace9f37fcccb,0x4675c7e5baafbffbca748158becba61ef3b0a263,2.027349e+17,21000,2357096623,0x,15889746,...,20390203,0x50251abb442a34c796c7d04515c5c5168eca258b0f64...,2.357097e+09,0.000000e+00,2,2357096623,NaN,[],NaN,NaN
1,0x90cbf1652e6b93adff4b155bf843f59ecfb239c06340...,90,113,0xeb549edf318fcbbed23cb3dd2323449e401ebd3c,0xde8f22fbc53add5da02cf75616ac8f1eeda07c68,4.390000e+18,21000,2648096623,0x,13441387,...,20390203,0x50251abb442a34c796c7d04515c5c5168eca258b0f64...,3.817832e+09,2.910000e+08,2,2648096623,NaN,[],NaN,NaN
2,0x58ce377546086d72e6a9ee83b9a2c09d820159e35b9e...,28,16,0x1225c2590a335b5dc20a67a07cf045245f463a4a,0xa5f565650890fba1824ee0f21ebbbf660a179934,7.798510e+14,49369,3847018376,0x02777bd5,921021,...,20390204,0x78fb6920b2a3d2578d9ba84be279f01a136f27e513f5...,3.873482e+09,1.472445e+09,2,3847018376,NaN,[],NaN,NaN
3,0x2ebff83a86344dc821152c7be90ca36cca1cb1ecb042...,375,49,0xa0a93347c540860d2ffc4891906cd1b8c2ccb921,0xd37bbe5744d730a1d98d8dc97c42f0ca46ad7146,0.000000e+00,450000,4139045669,0x1b738b32000000000000000000000000d37bbe5744d7...,5412686,...,20390205,0x3dce7866de8d6bcbe2cf2decf41eeb9fa73880394f93...,1.000000e+10,2.000000e+09,2,4139045669,NaN,[],NaN,NaN
4,0x45c1a3de70daccd2f2d767d89a3b60887444fcd8abbf...,0,9,0x0c9fdef04b350820c035174e7f755de7af169fc0,0x077d360f11d220e4d5d831430c81c26c9be7c4a4,1.563463e+16,22000,3000000000,0x,1384059,...,20390205,0x3dce7866de8d6bcbe2cf2decf41eeb9fa73880394f93...,NaN,NaN,0,3000000000,NaN,[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x056ad81d0edbb64521b011d9e5d0d4188f6416f47886...,98,94,0xcee4011e2e90d65a94b2ac5ed596c9834a607767,0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad,0.000000e+00,241011,2842724744,0x3593564c000000000000000000000000000000000000...,8325646,...,20302100,0x81d87f650570e14f6ccb94446142e5de15b010bc400e...,3.453106e+09,9.700000e+08,2,2842724744,NaN,[],NaN,NaN
99996,0x6b321aecf9f7b7fdebba7850a6c499e6b14245d75974...,127,6,0x3a0e3aa2524adff222a57aa611fd62a31065ad34,0x7a250d5630b4cf539739df2c5dacb4c659f2488d,0.000000e+00,315324,8967031119,0x791ac947000000000000000000000000000000000000...,1128992,...,20302101,0xa2b5cd7d9ffab6f1911449d3798f01063612c6e62d19...,1.457000e+10,7.140000e+09,2,8967031119,NaN,[],NaN,NaN
99997,0x9d326ec513a7ac96eb7ed54d32ba556b916be5a51cd2...,5,140,0x1db430f53d164e5a1fb431d66b7c2589b5a155c3,0xdac17f958d2ee523a2206206994597c13d831ec7,0.000000e+00,63507,1828031119,0xa9059cbb000000000000000000000000500b81835128...,16451783,...,20302101,0xa2b5cd7d9ffab6f1911449d3798f01063612c6e62d19...,2.157093e+09,1.000000e+06,2,1828031119,NaN,[],NaN,NaN
99998,0x38fc31f95e0322c1ff38be61a0f775b028d600d9a5d7...,11,124,0x806633d9d0c353802a5309885ded1aa6f6e0e2e6,0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad,0.000000e+00,274021,1828031119,0x3593564c000000000000000000000000000000000000...,14563342,...,20302101,0xa2b5cd7d9ffab6f1911449d3798f01063612c6e62d19...,2.009208e+09,1.000000e+06,2,1828031119,NaN,[],NaN,NaN
99999,0xfd914eb222171b30eda4ce6fee899e769710866e5251...,69,39,0x6e4ca415040a270a1e03c2ea6cc0c2b531de5d12,0xf3de3c0d654fda23dad170f0f320a92172509127,0.000000e+00,244850,2809738399,0x9871efa40000000000000000000000008802269d1283...,7101117,...,20302101,0xa2b5cd7d9ffab6f1911449d3798f01063612c6e62d19...,2.990287e+09,9.827073e+08,2,2809738399,NaN,[],NaN,NaN

In [86]:
data.columns

Index(['hash', 'nonce', 'transaction_index', 'from_address', 'to_address',
       'value', 'gas', 'gas_price', 'input', 'receipt_cumulative_gas_used',
       'receipt_gas_used', 'receipt_contract_address', 'receipt_root',
       'receipt_status', 'block_timestamp', 'block_number', 'block_hash',
       'max_fee_per_gas', 'max_priority_fee_per_gas', 'transaction_type',
       'receipt_effective_gas_price', 'max_fee_per_blob_gas',
       'blob_versioned_hashes', 'receipt_blob_gas_price',
       'receipt_blob_gas_used'],
      dtype='object')

| **Column Name**               | **Description**                                                                                      |
|-------------------------------|------------------------------------------------------------------------------------------------------|
| 1. `hash`                        | The unique identifier of the transaction, a cryptographic hash.                                      |
| 2. `nonce`                       | The transaction count from the sender's address, used to prevent replay attacks and ensure transactions are processed in the correct order. |
| 3. `transaction_index`           | The index of the transaction within the block, indicating the order of transactions in that block.   |
| 4. `from_address`                | The address of the sender of the transaction.                                                        |
| 5. `to_address`                  | The address of the recipient of the transaction.                                                     |
| 6. `value`                       | The amount of Ether being transferred in the transaction, measured in Wei.                          |
| 7. `gas`                         | The maximum amount of gas that the sender is willing to pay for the transaction to be executed.      |
| 8. `gas_price`                   | The price per unit of gas in Wei that the sender is willing to pay.                                  |
| 9. `input`                       | Additional data sent along with the transaction, often used for calling smart contracts.             |
| 10. `receipt_cumulative_gas_used` | The total amount of gas used by all transactions up to and including the current transaction in the block. |
| 11. `receipt_gas_used`            | The amount of gas actually consumed by the transaction's execution.                                  |
| 12. `receipt_contract_address`    | The address of a new smart contract created by the transaction (if applicable).                       |
| 13. `receipt_root`                | A field used in older versions of Ethereum, now replaced by `receipt_status`.                        |
| 14. `receipt_status`              | The status of the transaction's execution: 1 for success, 0 for failure.                            |
| 15. `block_timestamp`             | The timestamp of the block, indicating when the block was mined.                                     |
| 16. `block_number`                | The block number in which the transaction was included.                                              |
| 17. `block_hash`                  | The hash of the block that contains the transaction.                                                  |
| 18. `max_fee_per_gas`             | The maximum fee per unit of gas that the sender is willing to pay (includes both base fee and priority fee). |
| 19. `max_priority_fee_per_gas`    | The maximum priority fee per unit of gas that the sender is willing to pay to expedite the transaction. |
| 20. `transaction_type`            | The type of transaction (e.g., type 2 for EIP-1559 transactions).                                    |
| 21. `receipt_effective_gas_price` | The effective gas price paid for the transaction, taking into account the current base fee and priority fee. |
| 22. `max_fee_per_blob_gas`        | The maximum fee per unit of blob gas (specific to certain Ethereum Improvement Proposals).            |
| 23. `blob_versioned_hashes`       | Hashes of versions of blob data.                                                                       |
| 24. `receipt_blob_gas_price`      | The gas price for blob data.                                                                          |
| 25. `receipt_blob_gas_used`       | The amount of gas used for blob data.                                                                 |

In [87]:
# Преобразование wei в gwei
def wei_to_gwei(wei):
    return wei / 1e9

In [88]:
df = data[["gas", "max_fee_per_gas", "max_priority_fee_per_gas", "receipt_effective_gas_price", "block_timestamp", "gas_price"]]
label = df.loc[:, "gas_price"].apply(wei_to_gwei).astype(float)

# Применяем преобразование к колонкам что бы все было в одном формате цены
df.loc[:, 'max_fee_per_gas'] = df['max_fee_per_gas'].apply(wei_to_gwei).astype(float)
df.loc[:, 'max_priority_fee_per_gas'] = df['max_priority_fee_per_gas'].apply(wei_to_gwei).astype(float)
df.loc[:, 'receipt_effective_gas_price'] = df['receipt_effective_gas_price'].apply(wei_to_gwei).astype(float)

C:\Users\ivanz\AppData\Local\Temp\ipykernel_2148\750472374.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.35709662 2.64809662 3.84701838 ... 1.82803112 1.82803112 2.8097384 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'receipt_effective_gas_price'] = df['receipt_effective_gas_price'].apply(wei_to_gwei).astype(float)

In [89]:
df.isnull().sum() # проверка пропущенных значений

gas                               0
max_fee_per_gas                4142
max_priority_fee_per_gas       4142
receipt_effective_gas_price       0
block_timestamp                   0
gas_price                         0
dtype: int64

In [90]:
df.duplicated().value_counts() # количество НЕ дубликатов

False    92297
True      7703
Name: count, dtype: int64

In [91]:
# Обработка пропущенных значений, если есть
df = df.drop_duplicates() # удалить дубликаты

df = df.fillna(0)
label = label.fillna(0)
df = df.infer_objects()
label = label.infer_objects()

In [92]:
df.loc[:, "block_timestamp"] = pd.to_datetime(df["block_timestamp"], errors='coerce') # приводим дату к нормально виду в том случае если там есть ошибки
df = df.rename(columns={'block_timestamp': 'date'}) # переименовываем колонку с датой

In [93]:
# Убедимся, что преобразование прошло успешно
df['date'].head(16)

0     2024-07-26 10:43:35+00:00
1     2024-07-26 10:43:35+00:00
2     2024-07-26 10:43:47+00:00
3     2024-07-26 10:43:59+00:00
4     2024-07-26 10:43:59+00:00
5     2024-07-26 10:43:59+00:00
6     2024-07-26 10:43:59+00:00
7     2024-07-26 10:43:59+00:00
8     2024-07-26 10:43:59+00:00
9     2024-07-26 10:43:59+00:00
10    2024-07-26 10:43:59+00:00
11    2024-07-26 10:43:59+00:00
12    2024-07-26 10:44:11+00:00
13    2024-07-26 10:44:23+00:00
14    2024-07-26 10:44:23+00:00
15    2024-07-26 10:44:23+00:00
Name: date, dtype: object

In [94]:
# Убеждаемся, что индексы в df и label совпадают
df, label = df.align(label, join='inner', axis=0)

In [95]:
# Включение `gas_price` в DataFrame для графиков
df['gas_price'] = label
df

,gas,max_fee_per_gas,max_priority_fee_per_gas,receipt_effective_gas_price,date,gas_price
0,21000,2.357097,0.000000,2.357097,2024-07-26 10:43:35+00:00,2.357097
1,21000,3.817832,0.291000,2.648097,2024-07-26 10:43:35+00:00,2.648097
2,49369,3.873482,1.472445,3.847018,2024-07-26 10:43:47+00:00,3.847018
3,450000,10.000000,2.000000,4.139046,2024-07-26 10:43:59+00:00,4.139046
4,22000,0.000000,0.000000,3.000000,2024-07-26 10:43:59+00:00,3.000000
...,...,...,...,...,...,...
99995,241011,3.453106,0.970000,2.842725,2024-07-14 03:37:11+00:00,2.842725
99996,315324,14.570000,7.140000,8.967031,2024-07-14 03:37:23+00:00,8.967031
99997,63507,2.157093,0.001000,1.828031,2024-07-14 03:37:23+00:00,1.828031
99998,274021,2.009208,0.001000,1.828031,2024-07-14 03:37:23+00:00,1.828031
99999,244850,2.990287,0.982707,2.809738,2024-07-14 03:37:23+00:00,2.809738

In [96]:
if df['date'].isnull().any():
    print("Некорректные значения в столбце 'date':")
    print(df[df['date'].isnull()])

In [98]:
df["month"] = df["date"].dt.to_period("M")
monthly_avg = df.groupby("month")["gas_price"].mean().reset_index()

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
plt.figure(figsize=(12, 6))
plt.plot(monthly_avg['month'].astype(str), monthly_avg['gas_price'], marker='o', linestyle='-', color='b')
plt.title('Average Gas Price per Month')
plt.xlabel('Month')
plt.ylabel('Average Gas Price')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()

NameError: name 'monthly_avg' is not defined

In [ ]:
# Преобразование даты в Unix-время
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].astype(np.int64) // 10**9  # Преобразование в секунды

In [ ]:
# последняя проверка таблицы перед построением модели. Удаляем ненужные столбцы
df.drop(["date", "gas_price"], axis=1)

,gas,max_fee_per_gas,max_priority_fee_per_gas,receipt_effective_gas_price
0,21000,2.357097,0.000000,2.357097
1,21000,3.817832,0.291000,2.648097
2,49369,3.873482,1.472445,3.847018
3,450000,10.000000,2.000000,4.139046
4,22000,0.000000,0.000000,3.000000
...,...,...,...,...
99995,241011,3.453106,0.970000,2.842725
99996,315324,14.570000,7.140000,8.967031
99997,63507,2.157093,0.001000,1.828031
99998,274021,2.009208,0.001000,1.828031
99999,244850,2.990287,0.982707,2.809738

In [ ]:
x_train, x_temp, y_train, y_temp = train_test_split(df, label, test_size=0.4, random_state=42)
x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, train_size=0.5, random_state=42)

In [ ]:
# Нормализация данных
normalizer = Normalization(axis=-1)

In [ ]:
model = Sequential([
    normalizer,
    Input(shape=(6,)),
    Dense(64, activation="relu"),
])

In [ ]:
model.compile(optimizer="adam", loss="mse")

In [ ]:
history = model.fit(x_train, 
                    y_train, 
                    epochs=EPOCHS, 
                    batch_size=BATCH_SIZE, 
                    validation_data=(x_val, y_val))

Epoch 1/100

866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - loss: 13320439489101824.0000 - val_loss: 14664010752.0000
Epoch 2/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 659us/step - loss: 2529853696.0000 - val_loss: 54831028.0000
Epoch 3/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - loss: 48590200.0000 - val_loss: 29555718.0000
Epoch 4/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 653us/step - loss: 33096570.0000 - val_loss: 16398759.0000
Epoch 5/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 671us/step - loss: 14404828.0000 - val_loss: 9774046.0000
Epoch 6/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 642us/step - loss: 7053948.5000 - val_loss: 6464812.0000
Epoch 7/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 655us/step - loss: 4940425.5000 - val_loss: 4106480.7500
Epoch 8/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 686us/step - loss: 4176065.2500 - val_loss: 2461835.5000
Epoch 9/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 704us/step - loss: 886211.3125 - val_loss: 1308442.0000
Epoch 10/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 652us/step - loss: 1783408.8750 - val_loss: 706569.1250
Epoch 11/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 654us/step - loss: 596862.8125 - val_loss: 305954.7812
Epoch 12/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 660us/step - loss: 473850.0312 - val_loss: 126003.8672
Epoch 13/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 683us/step - loss: 33813.0430 - val_loss: 22630.6758
Epoch 14/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 652us/step - loss: 57171.4062 - val_loss: 3727.5371
Epoch 15/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 668us/step - loss: 15306.9121 - val_loss: 1170.6115
Epoch 16/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - loss: 2084.5210 - val_loss: 843.1562
Epoch 17/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 649us/step - loss: 10292.6338 - val_loss: 843.1320
Epoch 18/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 698us/step - loss: 6746.5386 - val_loss: 843.1807
Epoch 19/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 696us/step - loss: 1087.6473 - val_loss: 843.2075
Epoch 20/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 679us/step - loss: 2793.3113 - val_loss: 843.2075
Epoch 21/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 673us/step - loss: 2532.9399 - val_loss: 843.2075
Epoch 22/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 667us/step - loss: 27544.3008 - val_loss: 843.2075
Epoch 23/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 699us/step - loss: 9618.6035 - val_loss: 843.2075
Epoch 24/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - loss: 1186.5103 - val_loss: 843.2075
Epoch 25/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - loss: 19774.4727 - val_loss: 843.2075
Epoch 26/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 649us/step - loss: 9127.0195 - val_loss: 843.2075
Epoch 27/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 660us/step - loss: 4116.8984 - val_loss: 843.2075
Epoch 28/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 717us/step - loss: 3624.6023 - val_loss: 843.2075
Epoch 29/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - loss: 7749.5996 - val_loss: 843.2075
Epoch 30/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 652us/step - loss: 13523.2812 - val_loss: 843.2075
Epoch 31/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 646us/step - loss: 2806.6455 - val_loss: 843.2075
Epoch 32/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 669us/step - loss: 13900.2939 - val_loss: 843.2075
Epoch 33/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 654us/step - loss: 1139.2273 - val_loss: 843.2075
Epoch 34/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - loss: 3366.2529 - val_loss: 843.2075
Epoch 35/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 657us/step - loss: 1121.9883 - val_loss: 843.2075
Epoch 36/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 650us/step - loss: 11026.7188 - val_loss: 843.2075
Epoch 37/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 707us/step - loss: 5581.4766 - val_loss: 843.2075
Epoch 38/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - loss: 8347.8652 - val_loss: 843.2075
Epoch 39/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 648us/step - loss: 6952.0796 - val_loss: 843.2075
Epoch 40/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 664us/step - loss: 7872.5103 - val_loss: 843.2075
Epoch 41/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 675us/step - loss: 12366.5117 - val_loss: 843.2075
Epoch 42/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 664us/step - loss: 9419.9385 - val_loss: 843.2075
Epoch 43/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 658us/step - loss: 12186.5430 - val_loss: 843.2075
Epoch 44/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 661us/step - loss: 1465.0391 - val_loss: 843.2075
Epoch 45/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - loss: 12027.1875 - val_loss: 843.2075
Epoch 46/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 713us/step - loss: 1196.2859 - val_loss: 843.2075
Epoch 47/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - loss: 1863.0109 - val_loss: 843.2075
Epoch 48/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 670us/step - loss: 9321.2715 - val_loss: 843.2075
Epoch 49/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 667us/step - loss: 27336.0820 - val_loss: 843.2075
Epoch 50/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 666us/step - loss: 10092.1533 - val_loss: 843.2075
Epoch 51/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 656us/step - loss: 5752.4863 - val_loss: 843.2075
Epoch 52/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - loss: 9060.2861 - val_loss: 843.2075
Epoch 53/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 663us/step - loss: 11092.4834 - val_loss: 843.2075
Epoch 54/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - loss: 3874.2151 - val_loss: 843.2075
Epoch 55/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 741us/step - loss: 8554.2461 - val_loss: 843.2075
Epoch 56/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 652us/step - loss: 4120.4927 - val_loss: 843.2075
Epoch 57/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 660us/step - loss: 13153.5898 - val_loss: 843.2075
Epoch 58/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - loss: 7327.2427 - val_loss: 843.2075
Epoch 59/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 660us/step - loss: 915.7437 - val_loss: 843.2075
Epoch 60/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 654us/step - loss: 46752.9609 - val_loss: 843.2075
Epoch 61/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 656us/step - loss: 1910.4020 - val_loss: 843.2075
Epoch 62/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 682us/step - loss: 10122.0771 - val_loss: 843.2075
Epoch 63/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 722us/step - loss: 1368.4634 - val_loss: 843.2075
Epoch 64/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 657us/step - loss: 3201.2505 - val_loss: 843.2075
Epoch 65/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - loss: 10086.9365 - val_loss: 843.2075
Epoch 66/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 706us/step - loss: 2184.1895 - val_loss: 843.2075
Epoch 67/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 704us/step - loss: 713.8957 - val_loss: 843.2075
Epoch 68/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 713us/step - loss: 1188.2845 - val_loss: 843.2075
Epoch 69/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 757us/step - loss: 7827.2319 - val_loss: 843.2075
Epoch 70/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 678us/step - loss: 3069.0095 - val_loss: 843.2075
Epoch 71/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 655us/step - loss: 5372.5479 - val_loss: 843.2075
Epoch 72/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - loss: 9627.4736 - val_loss: 843.2075
Epoch 73/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 702us/step - loss: 1624.1768 - val_loss: 843.2075
Epoch 74/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 771us/step - loss: 10309.6982 - val_loss: 843.2075
Epoch 75/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 652us/step - loss: 7208.0693 - val_loss: 843.2075
Epoch 76/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 642us/step - loss: 8383.8799 - val_loss: 843.2075
Epoch 77/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 659us/step - loss: 2985.5374 - val_loss: 843.2075
Epoch 78/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - loss: 3687.5969 - val_loss: 843.2075
Epoch 79/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - loss: 2065.2954 - val_loss: 843.2075
Epoch 80/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - loss: 3971.9019 - val_loss: 843.2075
Epoch 81/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - loss: 9916.2705 - val_loss: 843.2075
Epoch 82/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 705us/step - loss: 13145.5996 - val_loss: 843.2075
Epoch 83/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - loss: 11250.8818 - val_loss: 843.2075
Epoch 84/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 644us/step - loss: 2602.5029 - val_loss: 843.2075
Epoch 85/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 672us/step - loss: 5194.5000 - val_loss: 843.2075
Epoch 86/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 689us/step - loss: 14519.8936 - val_loss: 843.2075
Epoch 87/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 703us/step - loss: 845.9355 - val_loss: 843.2075
Epoch 88/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 680us/step - loss: 2845.6965 - val_loss: 843.2075
Epoch 89/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - loss: 2091.6777 - val_loss: 843.2075
Epoch 90/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 668us/step - loss: 6966.1021 - val_loss: 843.2075
Epoch 91/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 668us/step - loss: 5491.5981 - val_loss: 843.2075
Epoch 92/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 669us/step - loss: 24562.5391 - val_loss: 843.2075
Epoch 93/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 704us/step - loss: 1920.2229 - val_loss: 843.2075
Epoch 94/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - loss: 5196.7324 - val_loss: 843.2075
Epoch 95/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 663us/step - loss: 7438.0811 - val_loss: 843.2075
Epoch 96/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - loss: 16451.3203 - val_loss: 843.2075
Epoch 97/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - loss: 10479.6660 - val_loss: 843.2075
Epoch 98/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 664us/step - loss: 6120.5708 - val_loss: 843.2075
Epoch 99/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 700us/step - loss: 13387.1367 - val_loss: 843.2075
Epoch 100/100
866/866 ━━━━━━━━━━━━━━━━━━━━ 1s 691us/step - loss: 3818.2871 - val_loss: 843.2075

In [ ]:
loss = model.evaluate(x_test, y_test)

577/577 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - loss: 1005.2770

In [ ]:
pred = model.predict(x_test)


df["new"] = pd.DataFrame(pred[0])
df

577/577 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step

,gas,max_fee_per_gas,max_priority_fee_per_gas,receipt_effective_gas_price,date,gas_price,new
0,21000,2.357097,0.000000,2.357097,1721990615,2.357097,0.0
1,21000,3.817832,0.291000,2.648097,1721990615,2.648097,0.0
2,49369,3.873482,1.472445,3.847018,1721990627,3.847018,0.0
3,450000,10.000000,2.000000,4.139046,1721990639,4.139046,0.0
4,22000,0.000000,0.000000,3.000000,1721990639,3.000000,0.0
...,...,...,...,...,...,...,...
99995,241011,3.453106,0.970000,2.842725,1720928231,2.842725,NaN
99996,315324,14.570000,7.140000,8.967031,1720928243,8.967031,NaN
99997,63507,2.157093,0.001000,1.828031,1720928243,1.828031,NaN
99998,274021,2.009208,0.001000,1.828031,1720928243,1.828031,NaN
99999,244850,2.990287,0.982707,2.809738,1720928243,2.809738,NaN